// Maintained automatically by the weekly update job (scripts/weekly-update-prompt.md).
// Newest entry first; capped at 20 entries. last_run updates on EVERY run, even no-change runs.
window.ATLAS_CHANGELOG = {
  "last_run": "2026-09-26 09:29",
  "entries": [
    {
      "date": "2026-09-26",
      "added": [],
      "upgraded": [],
      "note": "Checked — no changes. Discovery window Sep 25 09:23 → Sep 26 09:23: swept ~50 tracked orgs by lastModified, HF newest per pipeline (text-generation, image-text-to-text, text-to-image, text-to-video, image-to-video) since Sep 24, and trendingScore/likes7d top-40. Everything found was a finetune/quant of tracked models (Qwen3.8-27B, Qwen-Image-2.1, MiniMax-H3 churn), previously assessed (laya, needle3, Hemmingway-1, TeleOCR, Ternary-Bonsai, LensVLM-9B), or out of scope (ASR/diarization/music). CohereLabs tiny-aya-* metadata refresh (3B translation models, 9 likes) — not notable. Partial entries rechecked: LLaDA2.2-flash (no official active-param count yet) and DeepSeek-V4-Flash-Vision-Exp (unchanged since Sep 1) stay partial; Step-5-Preview-BF16 still 401; LTX-2.5 + North-Small-Translate still gated."
    },
    {
      "date": "2026-09-25",
      "added": [],
      "upgraded": [],
      "note": "Checked — no changes. Discovery window Sep 24 09:37 → Sep 25 09:23: swept ~50 tracked orgs by lastModified, HF newest per pipeline (text-generation, image-text-to-text, text-to-image, text-to-video, image-to-video) since Sep 23, and trendingScore top-40. Everything found was out of atlas scope, a finetune/quant, or previously assessed: apple LensVLM-9B (192 likes, new — a visual-text-compression inference framework SFT+RL post-trained on the tracked Qwen3.5-9B backbone with an Expand(k) tool; architecture identical to Qwen3.5-9B + ViT, novelty is the post-training recipe, skip per no-finetune rule — same precedent as Intern-S2-397B); nvidia NV-Reason-CT (medical-CT 3D-VLM finetune on a qwen3_5 backbone, 1 like); alibabagroup SparkWan2.1/2.2 (sparsity-pruned Wan video quants); iknownuting Sulphur-2-base (LTX-2.3 quant); memset0 vsqa-preview (Wan2.1 DMD NVFP4 quant); alibaba-pai Qwen-Image-2.1-Fun Controlnet/LoRA adapters; AikidoSec altar-1 (GLM-5.3 AWQ int4 quant); Akhilaaa3 Jev-Omni (gemma-4-12B finetune, assessed Sep 15); plus previously skipped convaiinnovations laya (non-autoregressive router, out of scope), TaichuAI ZDTaichu5.0-9B, netease-youdao Confucius4-R2T2 (ASR), m-a-p YuE2-3B (music) & SheetSage2 (music transcription), internlm InternLumina-U2 (still a README-only placeholder), inclusionAI Ling/Ring 2.x refresh (org-wide repo touch, no new models), internlm Intern-S2-397B (assessed Sep 24), AlexWortega openjev, TencentARC GAE-D64-1B (assessed Sep 24). Closed API-only news out of scope. Partial rechecks: inclusionAI/LLaDA2.2-flash lastModified 2026-08-20 unchanged (still no official active-param count); deepseek-ai/DeepSeek-V4-Flash-Vision-Exp 2026-09-01 unchanged (~297B stays estimated); stepfun-ai/Step-5-Preview-BF16 still HTTP 401 (weights promised Oct 15); CohereLabs/North-Small-Translate-1.0 and Lightricks/LTX-2.5 raw configs still gated (26th run). No upgrades. 68 models unchanged, v28."
    },
    {
      "date": "2026-09-24",
      "added": [],
      "upgraded": [],
      "note": "Checked — no changes. Discovery window covered only Sep 23–24 (last run added Ming-Image-0.1-Design yesterday): swept ~45 tracked orgs by lastModified, HF newest per pipeline (text-generation, image-text-to-text, text-to-image, text-to-video, image-to-video) since Sep 22, trendingScore + likes7d top-40, and web search for Sep 23–24 announcements. Everything found was out of atlas scope or previously assessed: black-forest-labs FLUX-3-Action base/so101/droid (7B world-action model outputting robot joint targets — robotics policy, its text encoder is the tracked Qwen3-VL-4B); TencentARC GAE-D64-1B + WorldCrafter-Fast (camera-control video adapters, no tech report — consistent with the Sep-22 WorldCrafter skip); nvidia Nemotron-3-Diarization + sortformer family (speaker diarization, ASR-adjacent) and NVIDIA-NemotronLabs-VoiceChat-11B (speech, pre-dates window); moondream parakeet-ultra/redux (ASR); internlm Intern-S2-397B re-assessed after its Sep-22 README/deployment-guide refresh — still Qwen3_5MoeForConditionalGeneration on the tracked Qwen3.5-397B-A17B backbone (60L/d4096/512-expert-top-10 Gated-DeltaNet 3:1 hybrid, 403.4B BF16 per weight index), a Shanghai AI Lab scientific-agent post-train — skip per no-finetune rule; XiaomiMiMo MiMo-V2.6-Distill-Qwen-9B (distill of tracked family); AlexWortega/openjev (Qwen3.5-4B reranker finetune); Altworld Hemmingway-1 (Qwen3.8-27B creative finetune, skipped Sep 21); stealth-model space-bunny-alpha (README-only placeholder, no weights); Sep-24 text-generation feed was zero-like GGUF/ONNX/SFT churn. Closed API-only news (Claude Opus 5.5, GPT-6 Sol/Luna) remains out of scope. Partial rechecks: inclusionAI/LLaDA2.2-flash lastModified 2026-08-20 unchanged (still no official active-param count); deepseek-ai/DeepSeek-V4-Flash-Vision-Exp lastModified 2026-09-01 unchanged (~297B stays estimated); stepfun-ai/Step-5-Preview-BF16 still HTTP 401 (weights promised Oct 15); CohereLabs/North-Small-Translate-1.0 and Lightricks/LTX-2.5 raw configs still 401-gated (25th run). No upgrades. 68 models unchanged, v28."
    },
    {
      "date": "2026-09-23",
      "added": [
        "ming-image-0-1-design"
      ],
      "upgraded": [],
      "note": "Added Ming-Image-0.1-Design (Ant Group inclusionAI, MIT, weights live Sep 17/announced Sep 22, verified against transformer/config.json + mllm/config.json + weight index + GitHub modeling code): a 6B graphic-design text-to-image model (UI, infographics, posters) with native RGBA transparent output and strong in-image text rendering. Generation core is a 6.15B-BF16 single-stream flow-matching DiT (30 blocks, 30 heads × 128, d 3840, SwiGLU FFN 10240, QK-RMSNorm, 3-axis RoPE 32/48/48, adaLN-Zero scale+gate modulation, 2 extra refiner blocks, FlowMatchEuler shift 6.0); conditioning comes from a 17B BailingMM2 MoE-VLM (BailingMoeV2 20L/2048d, 256 experts top-8, sliding window 4096 + Qwen2.5-ViT + Qwen2 text encoder) projecting hidden states at layers 5/12/20 to 2560-d caption features. Companion Ming-Image-0.1-Design-Layer (same DiT, multi_frame_output) decomposes flat designs into RGBA layers and is noted on the card rather than tracked separately. Skipped: GPT-6 Sol/Luna and Claude Opus 5.5 (closed API-only, no weights), NVIDIA–Hugging Face acquisition (not a model), plus the usual finetune/quant churn (Bonsai-2 GGUF wave, Qwen-Image-2.1 quants/LoRAs, MiMo-V2.6 distills). Partial rechecks: LLaDA2.2-flash (Aug 20) and DeepSeek-V4-Flash-Vision-Exp (Sep 1) unchanged, stay partial; Step-5-Preview-BF16 still 401-gated, North-Small-Translate-1.0 and LTX-2.5 still gated (24th run). 68 models, v28."
    },
    {
      "date": "2026-09-22",
      "added": [
        "mimo-v2-6-pro-rl",
        "mimo-v2-6-flash-rl",
        "aliceai-foundation-80b-a3b"
      ],
      "upgraded": [],
      "note": "Added Xiaomi MiMo-V2.6-Pro-RL and MiMo-V2.6-Flash-RL (MIT, open-sourced Sep 21 with tech report; verified against config.json + weight index + modeling code): omnimodal (text/image/video/audio) sparse-MoE agent models at 1M context trained by one mixed-domain asynchronous GRPO run with Groupwise Agentic Grading (GRS rubrics + GAR advantage redistribution) toward recursive self-improvement — Pro 1.02T/42B (70L/6144d, 384 experts top-8) and Flash 309B/15B (48L/4096d, 256 experts top-8), both on a hybrid full-GQA + sliding-window-128 attention backbone (10+60 and 9+39 layers, learned attention-sink bias, d_h 192/v 128, partial rotary 0.334) with a dense first block, MXFP4-stored releases (566 GB / 172.9 GB), and a 5-layer non-causal DFlash speculative draft decoder (Flash also carries 3 MTP layers); recomputed totals match the official counts 1.00x. Also added Yandex AliceAI-Foundation-80B-A3B-Base (Apache-2.0, Sep 12, never previously assessed): a from-scratch 80B/3B base with a 12x(3 KDA linear + 1 gated-attention) hybrid layout, 512 tiny experts top-10+1 shared, 262K context, shipped with new Russian factuality benchmarks. Skipped: StepFun Step-5 Preview (API-only Sep 20; official HF repo still a 401 placeholder, weights promised Oct 15; the public Step-5-Preview-BF16 mirrors carry step3p5v/Step4 configs — not primary sources), XiaomiMiMo/MiMo-V2.6-Distill-Qwen-9B (distill), upstage solar-pro4-tokenizer (tokenizer only), nvidia/Kumo-Forecast (time-series, out of scope), TencentARC WorldCrafter (no tech report), plus quant/LoRA churn. Partial rechecks: LLaDA2.2-flash (Aug 20) and DeepSeek-V4-Flash-Vision-Exp (Sep 1) unchanged, stay partial; North-Small-Translate-1.0 and LTX-2.5 still 401-gated (23rd run). 67 models, v27."
    },
    {
      "date": "2026-09-21",
      "added": [
        "qwen-image-2-1"
      ],
      "upgraded": [],
      "note": "Added Qwen-Image-2.1 (Alibaba, Qwen Research License, verified against transformer/config.json, weight index, the diffusers implementation and the official blog): a 7B / 32-layer single-stream flow-matching DiT that unifies text-to-image generation and image editing in one model, with native RGBA transparency (absorbs Dec-2025's Qwen-Image-Layered) and up to 10 reference images. Architecturally notable for its mixed-granularity block-causal mask — token-level causal across the packed [text ; reference latents ; target latents] stream, bidirectional inside each image block — plus a single shared SiLU+Linear(4096→4×4096) modulation tensor sliced by every block and a prefix KV cache valid because text/reference tokens modulate from t=0. Conditioned by a Qwen3-VL encoder (36L/4096d + 27L/1152d ViT), 64-ch residual VAE, 3-axis RoPE 16/56/56. The HF repo sat as a placeholder since Sep 14 and the weights + blog went live Sep 20, which is why the Sep-20 run missed it. Skipped this run: Altworld/Hemmingway-1 (114 likes, base_model finetune of tracked Qwen3.8-27B), XGENlabs/XGEN-JING (finetune of tracked MiniMax-H3), Cactus-Compute/needle3 (121M on-device tool-calling model, not frontier), Qwen-Image-2.1-PE-T2I/I2I (prompt-rewriter companion models), plus GGUF/LoRA churn (Bonsai-2, Qwen-Image-2.1 quants). Partial rechecks: LLaDA2.2-flash (lastModified Aug 20) and DeepSeek-V4-Flash-Vision-Exp (Sep 1) unchanged, stay partial; North-Small-Translate-1.0 and LTX-2.5 still 401-gated (22nd run). 64 models, v26."
    },
    {
      "date": "2026-09-20",
      "added": [
        "realtime-venus-omni"
      ],
      "upgraded": [],
      "note": "Added Realtime-Venus-Omni (Ant Group inclusionAI + Tsinghua, arXiv 2609.13814, Apache-2.0, verified against config.json + README + safetensors index): a 9B full-duplex realtime interaction model on the MiniCPM-o 4.5 / Omni-Flow backbone — Qwen3-8B language decoder (36L/4096d GQA 32/8), SigLIP2 vision tower + 64-query resampler, Whisper-Medium audio encoder with pool-5 projection, and discrete S3 speech tokens decoded by a bundled 20-layer Token2wav streaming flow-matching head. First model in the atlas built around a shared causal timeline: it perceives video+audio continuously, decides per-second listen-vs-speak, and emits in-stream <delegate> events executed asynchronously by an external harness (dual-loop runtime) so tools never block the dialogue; training-free long-video memory retrieves archived audio-visual evidence. Beats Gemini 3.1 Live and GPT-4o on Full-Duplex-Bench v1.5 continuation metrics (97/88/86%). Skipped this run: ginigen-ai/Edge-4B-TELL (verbatim Gemma-4-E4B q4_0 GGUF mirror + 10KB linear confidence probe — derivative), BAAI/Brainmu-Spike (spike-camera conv LoRA, out of scope), nvidia DeepSeek-V4.1-Flash-NVFP4 (quant of tracked model), MiniMax-H3 LoRA/GGUF churn, Johnny-Z/Anima-Light-Lavender (finetune). Partial rechecks: LLaDA2.2-flash and DeepSeek-V4-Flash-Vision-Exp unchanged, stay partial; North-Small-Translate-1.0 and LTX-2.5 still 401-gated (21st run). 63 models, v25."
    },
    {
      "date": "2026-09-19",
      "added": [],
      "upgraded": [],
      "note": "Checked — no changes. Scanned HF newest-models (text-generation, image-text-to-text, text-to-image, text-to-video, image-to-video; createdAt ≥ Sep 17), a ~40-org sweep (DeepSeek, Qwen, zai-org, THUDM, moonshotai, meta, Mistral, google, nvidia, MiniMax, inclusionAI, internlm, BAAI, Agnes-AI, openbmb, nex-agi, m-a-p, TaichuAI, ibm-granite, Lightricks, et al.) and trending/likes top-40, plus web search for Sep 18–19 announcements. Everything new was derivative, out-of-scope, or already assessed: PrismML Bonsai 2 27B (926-like GGUF wave, Sep 18 press) remains a ternary quant of tracked Qwen3.8-27B per its base_model tag — 2nd consecutive skip; Local-Axiom-AI/Sabaki-Preview is a 0-like untrained GGUF research toy; akoumpa/Moonlight-V4-16B-A3B is an explicitly *untrained* architecture-only config (tags: untrained, architecture-config); convaiinnovations/laya is a non-autoregressive decision/router model (reinforcement-learning pipeline, no config.json) out of atlas scope; kpsss34/Walkyrie-7B-MoE is gated (401) and a finetune of its own 1.3B base; the text-to-image/video window was LoRA and quant churn only (Johnny-Z/Anima-Light-Lavender = circlestone-labs/Anima finetune; Jossbgo/Qwen-Image-2512 is a re-upload of the Dec 2025 Qwen official release; Ternary-Bonsai MLX/GGUF, FastH3 MLX, LTX-2.5 FP8, Wan2.2 GGUF re-uploads). Web search surfaced only closed-weight or platform news (Alibaba Qwen3.8-Omni-Flash is an API audio model with no open weights; Kimi K3 Bedrock GA and GitLab-hosted K3/M3/GLM-5.3 are distribution news for tracked models; nvidia Nemotron-3.5-Lightning-30B-A3B and Gemma-4 NVFP4 pages pre-date the window, Aug/Apr releases). Partial rechecks: inclusionAI/LLaDA2.2-flash README (lastModified Aug 20) still discloses no official active-param count and deepseek-v4-flash-vision-exp is unchanged (lastModified Sep 1) — both stay partial; CohereLabs/North-Small-Translate-1.0 and Lightricks/LTX-2.5 raw configs still gated HTTP 401 (20th run). No upgrades. 62 models unchanged."
    },
    {
      "date": "2026-09-18",
      "added": [
        "gigachat3-5-reasoning",
        "xing4-0-29b-a4b"
      ],
      "upgraded": [],
      "note": "Added two open-weight frontier-class MoEs verified against HF config.json + README: GigaChat 3.5 Reasoning (Sber, 432B/28B, MIT — 256-expert top-8 + 1 shared over 30 GatedDeltaNet / 10 gated-MLA hybrid layers, ZeroCenteredGatedNorm pre+post, 3 MTP heads, six domain experts merged by online-RL + on-policy distillation, natively FP8-trained) and Xing4.0-29B-A4B (China Telecom, TeleChat lineage, 29B/4B Apache-2.0 — all-MLA MoE with 4-stream mHC hyper-connected residuals, 1 MTP draft layer, first model of its scale trained end-to-end on Ascend NPUs). Skipped as derivatives: prism-ml Ternary-Bonsai-2-27B (ternary quant of tracked Qwen3.8-27B per base_model tag), nvidia DeepSeek-V4.1-Flash-NVFP4, ZGCM-1-7B (small dense, no novelty). 62 models, v24."
    },
    {
      "date": "2026-09-17",
      "added": [],
      "upgraded": [],
      "note": "Checked — no changes. Scanned HF newest-models (text-generation, image-text-to-text, text-to-image, text-to-video, image-to-video; createdAt ≥ Sep 15), ~40-org sweep (DeepSeek, Qwen, zai-org, THUDM, moonshotai, meta, Mistral, google, nvidia, MiniMax, inclusionAI, internlm, BAAI, Agnes-AI, openbmb, nex-agi, m-a-p, TaichuAI, ibm-granite, Lightricks, et al.), trendingScore + likes7d top-40, and web search. Everything new since the last run was a derivative or re-upload of tracked/previously-assessed models: empero-ai/Qwen3.8-35B-A3B-Distill (12 likes) is an SFT distillation of tracked Qwen3.6-35B-A3B per its base_model tag — no-distill rule; harshatheg/Qwen-2.5-1B-RLCD (127 likes) is an MLX constrained-decoding finetune of Qwen2.5-1.5B-Instruct; CrowtherLabs/atom-proton-1.0 and Mapika/decider-2b-vision are Qwen3.8-27B-FP8 / Qwen3.5-2B finetunes; x-square-robot/X-Planner-9B and keepstar/Kali-Lite-Vision-9B are qwen3_5-arch domain VLMs; BAAI/Brainmu-Spike is a spike-camera reconstruction LoRA (out of atlas scope); internlm/Atria-Dawn-Preview-Ascend-w8a8 is a quant of the Sep-15-skipped Atria (config-identical to tracked GLM-5.2); PrismLive-2B/4B are MLX quants of gemma-4-E4B; TaichuAI/ZDTaichu5.0-9B-FP8/MLX/GGUF are quants of the already-assessed Sep-4 9B; plus the usual luganoquant/kingjones777/comatto/Abiray quant-GGUF wave over DeepSeek-V4.1-Flash, GLM-5.3-Flash, Kimi-K3, Agnes-3.0-Flash, Qwen3.8-Flash-Next, LTX-2.5, MiniMax-H3 and Wan2.2, the frtertaer LTX-2.5-uncensored FP8 re-upload, FastVideo-FastH3 LoRAs, and SDXL/Flux/Krea/Z-Image LoRA churn. Web search surfaced only closed-weight or derivative items (Abacus Smaug = Kimi-K3/V4-Flash/Qwen3.8-27B post-trains; State-of-Open-Source report mentions no new open weights). Partial rechecks: llada2-2-flash README still discloses no official active-param count (lastModified Aug 20) and deepseek-v4-flash-vision-exp is unchanged (lastModified Sep 1) — both stay partial; CohereLabs/North-Small-Translate-1.0 and Lightricks/LTX-2.5 still gated HTTP 401 (18th run). 60 models unchanged."
    },
    {
      "date": "2026-09-16",
      "added": [],
      "upgraded": [],
      "note": "Checked — no changes. Scanned HF newest-models (text-generation, image-text-to-text, text-to-image, text-to-video, image-to-video; createdAt ≥ Sep 14), ~40 org sweeps, trendingScore top-40, and web search. Everything new was a derivative or re-upload of tracked/previously-assessed models: Accio-Lab/occamy-1.0 (81 likes, the 'Alibaba co-work agent' in Sep 15 press) is an agentic post-train of Qwen3.6-35B-A3B per its own README (base_model tag) — skipped per the no-finetune rule; cloudyu/GLM-5.3-SLIM-E192 is an expert-pruned FP8 cut of GLM-5.3 (itself config-identical to tracked GLM-5.2); Cyclone-Labs/Solar-Griffin-26B-A4B is a mergekit merge of Gemma-4 finetunes; aoiandroid/LFM2.5-2.6B re-uploads the August LiquidAI release (pre-window); the inclusionAI *-singprobe wave (Sep 14) are eval probes of 15 tracked models; qikuanz/Spark-X2.5-4B and Sonorix/pulsar-v0.7 are a GGUF of an already-skipped 4B and a Qwen2.5-0.5B LoRA; nvidia foundationpose/c-foundationstereo are 3D pose/stereo models, out of atlas scope; the rest was the usual Qwen3.8/GLM-5.3/DeepSeek-V4.1 quant + SDXL/Wan/LTX LoRA churn. Web search surfaced only closed-weight items (Salesforce Koa pilot, TypeSafe Jev early-access). Partial rechecks: llada2-2-flash README still discloses no official active-param count and deepseek-v4-flash-vision-exp is unchanged (lastModified Sep 1) — both stay partial; CohereLabs/North-Small-Translate-1.0 and Lightricks/LTX-2.5 still gated HTTP 401 (17th run). 60 models unchanged."
    },
    {
      "date": "2026-09-15",
      "added": [],
      "upgraded": [],
      "note": "Checked — no changes. Two Shanghai AI Lab releases since Sep 13 were both post-trained variants of tracked architectures: internlm/Intern-S2-397B (40 likes) is Qwen3_5MoeForConditionalGeneration — the identical 60L/d4096/512-expert-top-10 Gated-DeltaNet 3:1 hybrid spec as the tracked Qwen3.5-397B-A17B — and internlm/Atria-Dawn-Preview (57 likes, agentic research model) is GlmMoeDsaForCausalLM with the exact GLM-5.2 config (78L/d6144/256 experts, MLA+DSA with 21-of-78 IndexShare layers), its README stating it is built on the 744B GLM-5.2 foundation — both skipped per the no-finetune-of-tracked-models rule (consistent with the Nex-N2.5 decisions). Also skipped: tencent/Simple-Attention-Sparsification (research attention-gate weights for Qwen3-4B/14B, arXiv 2609.13141), OPENGCM/GTM-3-base (75M single-GPU nanoGPT toy), zeromodels SD/SDXL re-uploads, and the DeepSeek-V4.1-Flash / Qwen3.8 / GLM-5.3 quant wave (soyrsoyr NVFP4/MXFP4/FP8 validation builds, MLX, GGUF, thoughtworks backdoor research checkpoints). Partial rechecks: llada2-2-flash README still discloses no official active-param count and deepseek-v4-flash-vision-exp is unchanged (lastModified Sep 1, ~297B stays estimated) — both remain partial; CohereLabs/North-Small-Translate-1.0 and Lightricks/LTX-2.5 still gated HTTP 401 (16th run). 60 models unchanged."
    },
    {
      "date": "2026-09-14",
      "added": [
        "agnes-3-0-flash",
        "aliceai-t5-35b-a0-6b"
      ],
      "upgraded": [],
      "note": "Added Agnes-3.0-Flash Preview (Sep 11, Agnes AI): a 33B dense multimodal hybrid-attention decoder in the gated-delta-net lineage — 54 delta-rule recurrent layers (16k/48v heads, conv k4, fp32 state) alternating 3:1 with 18 GQA global-attention layers (24q/4kv, d_h 256), so only 18 of 72 layers hold a growing KV cache; 262K context, parallel SwiGLU 2048 branch in every layer, 27L/1152d ViT, Apache-2.0, verified against config.json + README + 19-shard bf16 weights (66.2 GB). New 3:1 delta/global split diagram with a 72-tick layer strip. Also added Yandex AliceAI-T5-35B-A0.6B (Sep 10): a UL2-style encoder-decoder (16L encoder + 12L decoder, d1536) whose FFNs in all 28 layers are dMoE blocks with 512 tiny SwiGLU experts (d_ff 512) top-8 via a learned sigmoid router with L1-normalized weights and aux-loss-free bias updates — 34.35B unique but only ~0.6B active per token; 128K context via YaRN, tied shared embeddings, Apache-2.0, verified against config.json + README + 15-shard weights. Considered and skipped: Edge0-35B-A3B-preview (4-bit MLX quant of Qwen3.5-35B-A3B), NeoHorse-1-4B (Qwen3.5-4B finetune), Lotus-1 (Qwen3.5-35B-A3B RP finetune), Odette-26B-A4B (Gemma-4 merge), FlyGPT (fruit-fly-connectome toy), GeoCore-9B (domain DiT re-upload), the PYTHAI fork wave and the usual DeepSeek/Qwen/MiniMax-H3 quant wave. Partial rechecks: llada2-2-flash and deepseek-v4-flash-vision-exp disclosures unchanged — both stay partial (58/60 verified)."
    },
    {
      "date": "2026-09-13",
      "added": [],
      "upgraded": [],
      "note": "Checked — no changes. Scanned HF newest-models across text-generation, image-text-to-text, text-to-image and text-to-video since Sep 11, plus 16 major orgs (moonshotai, google, Qwen, deepseek-ai, THUDM, MiniMaxAI, zai-org, OpenBMB, inclusionAI, BAAI, Lightricks, CohereLabs, unsloth, meta-llama, stabilityai, mistralai): everything new was a quant/merge/finetune of tracked models (DeepSeek-V4.1-Flash GGUF/FP8/MLX wave, Qwen3.8-27B quants incl. abliterated GGUFs, MiniMax-H3 video derivatives, SD/Wan/Z-Image re-uploads). AlayaLab/Evoke-Turbo (Sep 11) is a controllability distill of the small Aug EVOKE world-model (26 likes) — not frontier, low traction, skipped; xagent2025/VelaVec-T2I is a 9.8M-param retrieval encoder, not a generator; BAAI/AIDD is a resource index, not a model. CohereLabs/North-Small-Translate-1.0 and Lightricks/LTX-2.5 both still gated HTTP 401 (LTX-2.5 — 14th run) so unverifiable from primary sources. Partial rechecks: llada2-2-flash README still discloses no official active-param count and deepseek-v4-flash-vision-exp is unchanged (lastModified Sep 1) — both stay partial (56/58 verified)."
    },
    {
      "date": "2026-09-12",
      "added": [],
      "upgraded": [],
      "note": "Checked — no changes. Scanned HF newest-1000 across text-generation, image-text-to-text, and image/video-gen filters since Sep 10: everything notable was a quant, merge, or finetune of tracked models (DeepSeek-V4.1-Flash GGUF/MLX/EXL3/NVFP4 wave, Boulesis-26B-A4B = Gemma-4 RP merge). nex-agi/Nex-N2.5-Pro weights went live (123 shards, Sep 11) but its config.json is Qwen3_5MoeForConditionalGeneration — a post-trained variant of the tracked Qwen3.5-397B-A17B architecture, skipped per the no-finetune rule. CohereLabs/North-Small-Translate-1.0 (218B/25B MoE translation model, announced Sep 10) is auto-gated — config.json and README both HTTP 401, so it cannot be verified from primary sources; revisit once ungated. thesysdev/OUI-1 (26B diffusion-Gemma generative-UI model, Sep 7) is a LoRA/adapter finetune of google/diffusiongemma-26B-A4B-it (June release, previously assessed) — skipped. Partial rechecks: deepseek-v4-flash-vision-exp README still discloses no total param count (~297B stays estimated) and llada2-2-flash still has no official active-param count — both remain partial."
    },
    {
      "date": "2026-09-11",
      "added": [
        "deepseek-v4-1-flash"
      ],
      "upgraded": [],
      "note": "Added DeepSeek-V4.1-Flash (Sep 10): a 552B-backbone/16B-decode-active native-multimodal MoE and the gallery's first Causal Encoder-Decoder — 20 causal encoder + 20 decoder layers whose global KV is projected from the final encoder hidden state, activating only 8B params during prefill and 16B during decode. It replaces V4's CSA/HCA hybrid with pure CSA2: every layer runs a 128-token SWA while the global branch is statically split into Full (4 layers: own main KV + indexer, Top-512), Reindex (4: shared KV, fresh indices, 2048-block candidate pool) and Reuse (30: shared KV + indices) modes — and FP4 (E2M1) main KV caching shrinks the global cache to 890 B/token (¼ of V4-Flash) with SWA Bounded Replay cutting persistent KV to ⅛. Also adds 196B Engram conditional memory (763B on disk incl. vision + 3 DSpark drafters), Single-Pass mHC, and DSpark speculative decoding — config.json + tech report + 510 GB weights verified. Considered and skipped: Lightricks LTX-2.5 LoRAs (base model still config-gated — 12th run), BAAI AIDD (no pipeline tag), NVIDIA DeepSeek-V4-Pro-0813-NVFP4-DSpark and MiniCPM5-2B-DSpark-GGUF (quants of tracked models), XHToken/Spark-X2.5-4B (4B dense, minor org), Nex-N2.5-Pro (weights still unreleased). Partial rechecks: deepseek-v4-flash-vision-exp and llada2-2-flash disclosures unchanged — both stay partial."
    },
    {
      "date": "2026-09-10",
      "added": [],
      "upgraded": [],
      "note": "Checked — no changes. The only notable release since the last run was nex-agi's Nex-N2.5 family (Sep 7-8): Nex-N2.5-Max is a post-trained variant of the DeepSeek-V4-Pro architecture already in the gallery (its config.json is the identical DeepseekV4ForCausalLM spec — 61L, d7168, 384 experts top-6+1 shared, hash-routed first 3 MoE layers, CSA/HCA, 1M context), and Nex-N2.5-mini/Pro are post-trained variants of the Qwen3.5-MoE hybrid architecture already covered by Qwen3.5-397B-A17B — both skipped per the no-finetune-of-tracked-models rule. Also skipped: Ling-3.0-flash-VL fp4/fp8/int4 quants, MiniCPM5-2B-DSpark-GGUF, NVIDIA NVFP4 quants, and Qwen3.8-Flash-Next-FP8 (all of models present). Partial rechecks: deepseek-v4-flash-vision-exp README still discloses no total param count (~297B stays estimated) and LLaDA2.2-flash still has no official active-param count — both remain partial. Note: the 2026-09-09 run deployed to GitHub Pages but its source-repo commit was missed; it was committed today as 6000f0f."
    },
    {
      "date": "2026-09-09",
      "added": [
        "ling-3-0-flash-vl",
        "llada-image"
      ],
      "upgraded": [],
      "note": "Added InclusionAI's Ling-3.0-flash-VL (Sep 4): a 124B/5.5B-active native-multimodal MoE whose 42-layer backbone alternates KDA linear attention and gated MLA 5:1 (35 KDA + 7 MLA, layer pattern verified from the safetensors weight map), 512 experts top-8 + 1 shared, clamped SwiGLU, and a Qwen3-style ViT feeding M-RoPE video positions — config + README + safetensors index verified (124.9B on disk, computed ratio 1.00). Also added LLaDA-Image (Sep 4, arXiv:2609.03796): a 6B single-stream flow-matching DiT conditioned by a FROZEN LLaDA2.0-Mini masked-diffusion VLM through a residual-query adapter + 6-layer connector — the gallery's first image generator with a diffusion-LLM text encoder, and open-source SOTA on Qwen-Image-Bench (53.53 EN / 53.38 ZH); DiT config + weights verified (6.54B on disk). Considered and skipped: openbmb/MiniCPM5-2B (2.5B dense Llama-arch on-device model, no architectural novelty — 2nd run), tencent/EVIE-8B/4.5B (Colbert retrieval heads on a Qwen3.5 base — niche, 2nd run), inclusionAI/Ling-3.0-flash-VL-fp8 (quant of a tracked-family model), IFM K2-Horizon-32B (still Stage-1, final checkpoint unreleased), Lightricks LTX-2.5 (config still gated HTTP 401 — 11th run), BAAI ConsiSpace (Qwen2.5-VL-3B + VGGT geometry head — derivative, small). Partial rechecks: deepseek-v4-flash-vision-exp README still discloses no total param count and llada2-2-flash still has no official active count — both stay partial."
    },
    {
      "date": "2026-09-08",
      "added": [
        "llada2-2-flash",
        "llada2-2-mini"
      ],
      "upgraded": [],
      "note": "Added the LLaDA2.2 agentic diffusion-language-model family from Ant Group's InclusionAI — the gallery's first masked-diffusion LLMs (bidirectional attention, parallel block generation, Levenshtein Editing via DELETE/INSERT control tokens, Block Routing bounding MoE activation per 32-token block, L-EBPO agentic RL). LLaDA2.2-flash: 100B MoE, 32 layers, 256 experts top-8 + 1 shared, 128K context (config-verified; active params not officially disclosed — ~4.9B derived, so confidence=partial on that field alone). LLaDA2.2-mini (released 2026-09-05): 16B/1.4B active, 20 layers, same routing scheme (verified). Considered and skipped: openbmb/MiniCPM5-2B (dense Llama-arch 2B on-device model — no architectural novelty, small scale), tencent/EVIE-8B & 4.5B (visual-document-retrieval Colbert heads on a Qwen3.5 base — retrieval niche, previously skipped), Viggle/Viggle-Animate (MiniMax-H3 video blocks repackaged as pt2 modules — derivative), inclusionAI/LLaDA-Image (Aug 28 diffusion image generator built on LLaDA2 text encoder — outside the discovery window, revisit next run for the image-gen slot), Novasy/nova-video-gen (CogVideoX-2b re-upload), BAAI/ConsiSpace (still a zip dump). DeepSeek-V4-Flash-Vision-Exp re-checked: README still discloses no total param count — ~297B estimate and partial confidence stand."
    },
    {
      "date": "2026-09-07",
      "added": [
        "k2-horizon-375b-a23b",
        "k2-horizon-mova-36b-a4b"
      ],
      "upgraded": [],
      "note": "Added the K2-Horizon family from IFM (LLM360 lineage, Apache-2.0, released 2026-09-04): the 375B-A23B open MoE flagship (375B/23B active, 61 layers, 192 experts top-8 + 1 shared, 3 dense head layers, 512K context, partial-RoPE GQA) and the architecturally novel MoVA-36B-A4B — Mixture-of-Values attention, where 45 of 48 layers replace v_proj with 64 routed value experts (top-4, sigmoid) plus a per-head softplus output gate, stacked on a 100-expert FFN MoE. Both verified from the official config.json, README, modeling code, and safetensors index (379.2B raw params). Considered and skipped: K2-Horizon-32B (Stage1 intermediate checkpoint, final pending), 7B/3.7B/0.9B family members (not notable), Kimi-Linear-48B-A3B (2025 release), Zing-0.5 world model (Wan2.2-TI2V-5B derivative), and OpenAI GPT-6 Astra / World Labs Atlas (proprietary, no open weights)."
    }
  ]
};
