// Maintained automatically by the weekly update job (scripts/weekly-update-prompt.md).
// Newest entry first; capped at 20 entries. last_run updates on EVERY run, even no-change runs.
window.ATLAS_CHANGELOG = {
  "last_run": "2026-10-06 09:40",
  "entries": [
    {
      "date": "2026-10-06",
      "added": [],
      "upgraded": [],
      "note": "Checked — no changes. Discovery window Oct 5 09:40 → Oct 6 09:40 CST (~24h): swept ~66 tracked orgs by lastModified, HF newest per pipeline (text-generation, image-text-to-text, text-to-image, image-to-image, text-to-video, image-to-video, any-to-any, text-to-audio, video-to-video) created in-window, likes7d top-200 and trendingScore top-150 filtered to in-window creations, plus web news. The window's one headline is Reflection AI's Beam (501B/23B sparse MoE, 23.8T tokens, 1M context, Apache-2.0, announced Oct 5 blog) — but weights are not on HuggingFace yet (no reflection-ai org, guessed repo names 401; the blog and TechCrunch both say weights + tech report land later this month), so it is skipped per the placeholder rule and added to the watch list for next run. Everything else was derivative churn: facebook/meta-encoder (Muse-Glimmer-taged feature-extraction/similarity encoder, config 401, out of atlas modalities), facebook/sam3 (SAM 3 released Nov 2025 — outside atlas modalities, not an in-window release; merely re-trending), autotrust/GEV-26B-Decide + JEV-27B-VL (gemma4/Qwen3.8-27B decision-model class — standing skip, JEV/Clef precedent), AEON-7 Qwen3.6/3.8 uncensored quant refreshes, google/DiarizationLM-Gemma-4-E4B-v1 (speaker diarization, out of scope), ibm-granite/granitelib-core-r1.0 (LoRA/PEFT library checkpoint), nvidia/music-flamingo-hf + Kumo-Tabular metadata touches (music understanding / tabular, out of scope), and the usual zero-like GGUF/MLX/FP8/LoRA quant churn over tracked models. Partial rechecks: LLaDA2.2-flash (mod Aug 20) and DeepSeek-V4-Flash-Vision-Exp (mod Sep 1) unchanged — stay partial; Step-5-Preview-BF16, Kimi-K3-Base, CohereLabs/North-Small-Translate-1.0 and Lightricks/LTX-2.5 all still HTTP 401 gated. 72 models unchanged, v32."
    },
    {
      "date": "2026-10-05",
      "added": [
        "iquest-q1"
      ],
      "upgraded": [],
      "note": "Added IQuest-Q1 (320.3B/15B sparse MoE, Modified MIT, verified): an agentic-CLI foundation model benchmarked against DeepSeek-V4 on Terminal-Bench/CyberGym/HLE, with 88 layers in a 25-full + 63-sliding-window (4096) hybrid attention pattern, partial 32-dim RoPE with dual thetas, fused sink attention, a dense layer-0 FFN, 256 experts top-8 (fused tensors), sandwich RMSNorm, and a separate recursive-×8 MTP module for speculative decoding. Considered and skipped: Cloudflare Clef (Qwen3.8-27B decision-model finetune, no-finetune rule), BFL FLUX 3 Image (launched Oct 2 but open weights not shipped — commercial license only for now), google/DiarizationLM-Gemma-4-E4B-v1 (speaker-diarization task model, out of scope)."
    },
    {
      "date": "2026-10-04",
      "added": [
        "kolibri-1"
      ],
      "upgraded": [],
      "note": "Added Aleph Alpha Kolibri 1 (78.1B/3.46B, Apache-2.0, verified): the first frontier-scale sovereign-EU open-weight release — trained end-to-end in Germany/Finland on 24T tokens with a public 189-page tech report. Architecturally notable on three axes: (1) the most aggressive sparse-MoE shape in the atlas — 384 very narrow routed experts (d_ff 512) with only 6 firing per token plus 1 shared, i.e. 4.4% activation and zero leading dense layers; (2) a strict 4:1 sliding/full attention interleave (40 SWA @ window 512 + 10 full) where RoPE is applied ONLY in the sliding layers and the full-attention layers carry NO positional encoding, which lets the 262K native context extend to 1M with no position scaling; (3) sandwich normalisation (RMSNorm before and after both sublayers) and a sigmoid router without top-k renormalisation, load-balanced by Exact Quantile Balancing. Param math reproduces the official 78,103,074,560 total to within 2,560 params. The HF release is FP8 (128×128 blocks) with embeddings/LM head/norms/routers kept in BF16; the BF16 twin carries an identical config. Discovery note: the repo was created Oct 2 as a placeholder and the weights + blog landed Oct 3, so a createdAt-in-window sweep would have missed it — caught via the likes7d trending sweep. Skipped this window: IFM K2-Horizon FP8/NVFP4 quant refreshes, allenai/AstaBrief_8B (Qwen3 DPO finetune), Cloudflare Clef + laya (decision-router class, unchanged), and the usual zero-like GGUF/LoRA churn."
    },
    {
      "date": "2026-10-03",
      "added": [],
      "upgraded": [],
      "note": "Checked — no changes. Discovery window Oct 2 09:47 → Oct 3 09:23 CST: swept ~56 tracked orgs by lastModified, HF newest per pipeline (text-generation, text-to-image, image-to-image, text-to-video) created in-window, trending top-60 and top-100-by-likes since Sep 25, plus web news (openmodelweights.com Oct 2 briefs). The window was quiet — no primary-source frontier or architecturally novel release. Considered and skipped: PixilabAI/Blink-v0.3-26B-A4B-{FP8,NVFP4} (Oct 2; decision-model finetunes of google/gemma-4-26B-A4B — base gated 401, no free-form generation — no-finetune rule + established decision-router class skip, Clef/JEV-27B precedent), microsoft/FrogNano-4B-2609 (Oct 2 mod; compact repo-level coding agent, RL-post-trained from Qwen/Qwen3.5-4B with no stronger-model trajectories — interesting training story but an unchanged qwen3_5 3:1 GatedDeltaNet/gated-attention hybrid finetune, no-finetune rule), allenai/AstaBrief_8B (Oct 2 mod; Qwen3-8B DPO deep-research finetune), ZhengmingYu/DMAD (Oct 2, 24 likes; 4-step audio-video distillation LoRAs/full weights over tracked MiniMaxAI/MiniMax-H3 — base_model:adapter, distill rule), IFM/LoopedLM-P2-* (Oct 2 mods; ~28 zero-like research-ablation checkpoints for the looped-LM Part-II paper, xLLM-format s/m huginn/parcae variants — not notable), nvidia/NemotronLabs-AI-for-Media-Sports-Tennis (Oct 2 mod; Nemotron-3-Nano-Omni any-to-any finetune, previously skipped), nvidia/c-fast-foundationstereo (stereo-depth ONNX, out of scope), nvidia/PixelDiT2-ImageNet (raw .ckpt research artifacts, no card/config), black-forest-labs/flux-3-action-{base,so101,droid} (Oct 2 mods; robotics world-action models already skipped Sep 22 as out-of-atlas-scope — mod was metadata only), m-a-p/SheetSage2 + ibm-granite/granite-speech-5.0 (audio/music modalities, out of scope), Lightricks/LTX-2.3+2.5 (Oct 2 mods; configs still HTTP 401 gated — 34th run, mod was repo maintenance not new weights), and the usual Qwen3.x/Qwen-Image-2.1/GLM-5.3/MiniMax-H3/MiMo-V2.6 GGUF-MLX-NVFP4-uncensored-LoRA churn (willhx, TheDrainFlorist, OpenFlowLM NPU2 conversions, yamz-labs, tstepspam, OsaurusAI, mlboydaisuke CoreAI port etc). Web news: llama.cpp System-One decision endpoint (runtime), Olmo-core 3 (training infra, already noted Oct 2), NVIDIA–HuggingFace acquisition agreement (ecosystem news) — no new models. Partial rechecks (step 3): LLaDA2.2-flash (mod Aug 20) and DeepSeek-V4-Flash-Vision-Exp (mod Sep 1) unchanged, stay partial; Step-5-Preview-BF16, CohereLabs/North-Small-Translate-1.0 and Lightricks/LTX-2.5 raw configs still HTTP 401 gated; moonshotai/Kimi-K3-Base/-Instruct still 401, Kimi-K3 tracked entry unchanged (mod Sep 2). 70 models, v30 unchanged."
    },
    {
      "date": "2026-10-02",
      "added": [],
      "upgraded": [],
      "note": "Checked — no changes. Discovery window Oct 1 09:23 → Oct 2 09:23 CST: swept ~55 tracked orgs by lastModified, HF newest per pipeline (text-generation, image-text-to-text, text-to-image, text-to-video, image-to-video, audio-text-to-text, text-to-audio, any-to-any) since Oct 1, and trendingScore/likes7d top-40, plus web search for Oct 1–2 announcements. The window's headline release was Cloudflare's first open models, Clef + Clef-Flash (336/107 likes, Oct 1 blog): multimodal decision models post-trained from tracked Qwen3.8-27B / Qwen3.5-9B (base_model:finetune tags) that return one logit per schema option via a joint-schema head with no free-form text generation — skipped per the no-finetune rule and the established decision-router/classifier class skip (laya, Julia-1, Jev-Omni, JEV-27B, OpenDecider precedents). nvidia/PixelUMM (Oct 1, silent research drop, 5 likes): 15.2B unified multimodal on a Qwen3-8B backbone (base_model:finetune tag), restrictive 'other' license, no NVIDIA announcement — skipped per no-finetune rule (LensVLM-9B precedent); watching in case NVIDIA officially launches it. FINAL-Bench/Darwin-180B-RSI (98 likes, Sep 28; R3 finetune + GGUF quant Oct 1–2): RSI self-improvement post-train of tracked Qwen3.8-Flash-Next — README lineage table is explicit ('Parent: Qwen/Qwen3.8-Flash-Next'; 512 routed experts, router and vision encoder preserved untouched; config is the same qwen4_exp 3:1 linear/full hybrid) — skipped per no-finetune rule. Also skipped: metaresearch/Muse-Glimmer-30B (0-like third-party re-upload of tracked meta-models model — not primary), Synin/Synin-1.0-Omni-Inquisitive (README is a verbatim Qwen3-Omni copy — re-upload/finetune), gowdavidwan2003/ARACHNE-FOUNDATION-50B (0-like experimental 'NULLXES' video DiT, no official backing, marketing-heavy card), nvidia/PixelDiT2-ImageNet (ImageNet class-conditional DiT research artifact, no model card), eulogik/nirnay-450m (450M decision classifier — out-of-scope class), PSRben/VisionHOPE (image classification), FermionResearch/Phonon-2 (parakeet-tdt-0.6b MLX quant — ASR + quant), abdur-rahman97/Dahono-4B (Qwen3.5-4B-Base legal finetune), deepseek-ai/DeepSeek-V4.1-Flash Oct 1 'Adding chat template' commit (tracked, no spec change), IFM K2-Horizon family + black-forest-labs/flux-3-action-base ('Add root config.json manifest') + BAAI/AREX-2 metadata-only touches, Lightricks LTX-2.5-IC-LoRA (LoRA of gated tracked model), OsGo gemma-4 QAT variants, MiniMax-Music3/ACE-Step-1.5 mirrors, MiniMax-H3 ComfyUI workflow churn, allenai Olmo-core 3 (training infrastructure, not a model), Gemini 4 Argon (closed API). Partial rechecks: LLaDA2.2-flash (mod Aug 20) and DeepSeek-V4-Flash-Vision-Exp (mod Sep 1) unchanged, stay partial; Step-5-Preview-BF16, North-Small-Translate-1.0 and LTX-2.5 still HTTP 401 gated (33rd run). 70 models, v30 unchanged."
    },
    {
      "date": "2026-10-01",
      "added": [
        "naive-n0-5-flash"
      ],
      "upgraded": [],
      "note": "Added NaiveAI Naive-N0.5-Flash (309B/15.5B, MIT, verified): the first open-weight release from the AI-centered-R&D lab we had been watching as 'naiveailab' (the real HF org is NaiveAI). Architecturally notable because it has NO full-attention layers at all — 39 sliding-window layers (window 128) interleaved with 9 lightweight-DSA layers (DeepSeek Sparse Attention rebuilt on GQA4 instead of MLA; 16-head fp8 indexer selects top-2,048 tokens) in a 5:1 pattern — giving native 1M context with flat decode cost. DeepSeek-V3-style 256-expert top-8 sigmoid/noaux_tc routing with no shared expert and a single dense first layer; continued-pretrained 3.25T tokens from Xiaomi's open MiMo-V2.5 base. Specs verified against HF config.json, in-repo modeling code, README table and the naive.ai research blog; computed param total (309.4B) matches the claimed 309B. Skipped this window: BAAI/AREX-2 (Qwen3.8-27B finetune), apple/LensVLM-9B (Qwen3.5-9B finetune), TaichuAI/ZDTaichu5.0-9B (custom_code, previously assessed), prism-ml Ternary-Bonsai-2 (2-bit ternary quant of Qwen3.8-27B), convaiinnovations/laya + SupersonicLabs/Julia-1 (decision-router classifiers, no LLM decoder), Edge0/Audio8-ASR-Infinite (ASR pipeline, out of atlas modalities). Partial rechecks: LLaDA2.2-flash (mod Aug 20) and DeepSeek-V4-Flash-Vision-Exp (mod Sep 1) unchanged, stay partial; Step-5-Preview-BF16, North-Small-Translate-1.0 and LTX-2.5 still HTTP 401 gated (32nd run). 70 models, v30."
    },
    {
      "date": "2026-09-30",
      "added": [],
      "upgraded": [],
      "note": "Checked — no changes. Discovery window Sep 29 09:31 → Sep 30 09:23: swept ~50 tracked orgs by lastModified, HF newest per pipeline (text-generation, image-text-to-text, text-to-image, text-to-video, image-to-video, audio-text-to-text) since Sep 28 23:00, and trendingScore/likes7d top-40. Everything found was a finetune/quant of tracked models or out of scope: BAAI/AREX-2 (Sep 29; base_model:finetune of Qwen/Qwen3.8-27B deep-research agent — no-finetune rule, Holo4/JEV-27B precedent), freelawproject/surya-ocr-2 + dots.mocr (Sep 29; OCR doc-parsing models, surya-ocr-2 tagged qwen3_5 finetune — same skip as TeleOCR), internlm/AdvancedMathBench-AutoVerifier (Sep 29; qwen3_5_moe math proof-verifier finetune), inclusionAI/Ming-flash-omni-2.0 (mod Sep 29 was README + TDS-summary-PDF upload only; Feb release unchanged), nvidia/cbottle (Sep 29 mod; FourCastNet-style weather diffusion, non-LLM), nvidia/GLM-5.3-Flash-NVFP4 + SOMA-X + AI-for-Media-Sports-Tennis metadata refreshes, Efficient-Large-Model/LongLive-Plug-* (Wan/MiniMax-H3 long-video plugins, not standalone models), IFM/K2-Horizon family (Sep 28 mods only; tracked), and the usual GLM-5.3/Qwen3.8-27B/Qwen-Image-2.1/MiMo-V2.6-MOPD/Holo4 GGUF-NVFP4-MLX-LoRA quant churn (bartowski/AxionML/DavidAU/ISTA-DASLab/unsloth etc). naiveailab org still 401/empty — watching for the Jifeng Dai first release. Partial rechecks: LLaDA2.2-flash (mod Aug 20) and DeepSeek-V4-Flash-Vision-Exp (mod Sep 1) unchanged, stay partial; Step-5-Preview-BF16, North-Small-Translate-1.0 and LTX-2.5 still HTTP 401 gated (31st run). 69 models unchanged, v29."
    },
    {
      "date": "2026-09-29",
      "added": [],
      "upgraded": [],
      "note": "Checked — no changes. Discovery window Sep 28 09:35 → Sep 29 09:24: swept ~55 tracked orgs by lastModified, HF newest per pipeline (text-generation, image-text-to-text, text-to-image, text-to-video, image-to-video, audio-text-to-text) since Sep 27, and trendingScore/likes7d top-40. The window's headline release is H Company's Holo4 family (blog Sep 28, weights landed Sep 24): Holo4-27B is a computer-use VLM tagged base_model:finetune of the tracked Qwen/Qwen3.8-27B (Qwen3_5ForConditionalGeneration, 64L/5120d linear+full 3:1 hybrid, cc-by-nc-4.0), Holo4-35B-A3B is a finetune of Qwen/Qwen3.6-35B-A3B (apache-2.0), and Holotron4-30B-A3B is a NemotronH-Nano-Omni finetune — agentic post-trains of existing architectures, skipped per the no-finetune rule (LensVLM-9B / Intern-S2-397B precedent). Also skipped: autotrust/JEV-27B (Sep 27 blog; Qwen3.8-27B decision-model student distilled from TypeSafe Jev outputs — distill + out-of-scope router class), manjunathshiva OpenDecider (400M Ettin-encoder / Qwen3-4B-LoRA decision models, out of scope), SIZWL/NVIDIA-Nemotron-3-Super-120B-A12B-BF16 (third-party re-upload of the March nvidia release), nvidia metadata refreshes (Kumo-Relational = TabICL finetune, Kumo-Tabular = tabular foundation model, SOMA-X = parametric human-body model, NV-Generate-CT = medical latent diffusion, AI-for-Media-Sports-Tennis = Nemotron-3-Nano-Omni any-to-any finetune — all non-LLM or finetunes), BernaLabs berna-r7 (from-scratch 0-like toy), yava-code Tessera-1B-Nano (SmolLM2-360M concept-LM), introvoyz043 BioMatrix-1.7B (Qwen3-1.7B finetune), 0xSojalSec REDCELL-26B-A4B (gemma-4 finetune), and the usual zero-like GLM-5.3/Qwen3.8-27B/Qwen-Image-2.1/LTX-2.5/MiniMax-H3 GGUF-quant-LoRA churn. naiveailab (Jifeng Dai startup) still has no HF org/models — watching. GPT-6 Astra DevDay news (Sep 29) is closed API-only, out of scope. Partial rechecks: LLaDA2.2-flash (mod Aug 20) and DeepSeek-V4-Flash-Vision-Exp (mod Sep 1) unchanged, stay partial; Step-5-Preview-BF16 still HTTP 401 (weights promised Oct 15); North-Small-Translate-1.0 and LTX-2.5 still gated (30th run). 69 models unchanged, v29."
    },
    {
      "date": "2026-09-28",
      "added": [],
      "upgraded": [],
      "note": "Checked — no changes. Discovery window Sep 27 09:37 → Sep 28 09:25: swept ~55 tracked orgs by lastModified, HF newest per pipeline (text-generation, image-text-to-text, text-to-image, text-to-video, image-to-video, audio-text-to-text) since Sep 27, and trendingScore/likes7d top-40. The only fresh official releases were XiaomiMiMo/MiMo-V2.6-{Flash,Pro}-MOPD (Sep 27) — explicitly the MOPD2 multi-teacher on-policy-distillation upgrade of the already-tracked MiMo-V2.6-{Flash,Pro}-RL checkpoints (same MiMoV2ForCausalLM architecture, 48L/9-full+39-SWA hybrid unchanged); skip per no-distill rule — same precedent as MiMo-V2.6-Distill-Qwen-9B. Qwen3Guard-Stream-* were Sep-2025 guard classifiers with a metadata refresh; SupersonicLabs/Julia-1 (195 likes) is a 144M mmBERT-small decision/router classifier — not frontier, out of scope; tsinghua VeriLoop-E2 is a Qwen3.8-27B post-train. naiveailab (Jifeng Dai's Tencent-backed startup rumored to drop its first open-weight LLM this month) has no HF org/models yet — watching. Partial rechecks: LLaDA2.2-flash (mod Aug 20) and DeepSeek-V4-Flash-Vision-Exp (mod Sep 1) unchanged, stay partial; Step-5-Preview-BF16 still HTTP 401 (weights promised Oct 15); North-Small-Translate-1.0 and LTX-2.5 still gated (29th run). 69 models unchanged, v29."
    },
    {
      "date": "2026-09-27",
      "added": [
        "internlumina-u2"
      ],
      "upgraded": [],
      "note": "Added InternLumina-U2 (Shanghai AI Lab, Apache-2.0; weights landed Sep 24 after a Sep 1 README-only placeholder — verified against nvidia/config.json + weight index + GitHub inference code): a 16B-A1B fully-discrete multi-codebook unified model — a LLaDA-2.0 MoE masked-diffusion backbone (20L/2048d, 256 experts top-8 + 1 shared, first layer dense) handles text QA, text-to-image generation, image editing and image/video/3D understanding through one discrete-token interface. Visual positions use Apple's AToken tokenizer with 8 complementary codebooks: input-side the 8 per-codebook embeddings concatenate and project into a single backbone token; output-side the dLLM denoises masked spatial positions in parallel while a codebook-depth AR head predicts each position's 8 codes. Dual Ascend/NVIDIA-trained checkpoints ship in one repo; on-disk 16.9B BF16 vs the official 16B claim (computed ratio 0.98). Skipped: internlm Intern-Decision-0.8/2/4B (Qwen3.5-0.8/2/4B decision-making finetunes), orcarouter OrcaSAQ-2-27B (Qwen3.8-27B exl3 3-bit quant + agentic post-train), Contrastive-LM CLM-v0.1-8B (assessed Sep 26), and the usual Qwen3.8-27B / Qwen-Image-2.1 / MiniMax-H3 GGUF-MLX-LoRA churn. Partial rechecks: LLaDA2.2-flash (Aug 20) and DeepSeek-V4-Flash-Vision-Exp (Sep 1) unchanged, stay partial; Step-5-Preview-BF16, North-Small-Translate-1.0 and LTX-2.5 still gated (28th run). 69 models, v29."
    },
    {
      "date": "2026-09-26",
      "added": [],
      "upgraded": [],
      "note": "Checked — no changes. Discovery window Sep 25 09:23 → Sep 26 09:23: swept ~50 tracked orgs by lastModified, HF newest per pipeline (text-generation, image-text-to-text, text-to-image, text-to-video, image-to-video) since Sep 24, and trendingScore/likes7d top-40. Everything found was a finetune/quant of tracked models (Qwen3.8-27B, Qwen-Image-2.1, MiniMax-H3 churn), previously assessed (laya, needle3, Hemmingway-1, TeleOCR, Ternary-Bonsai, LensVLM-9B), or out of scope (ASR/diarization/music). CohereLabs tiny-aya-* metadata refresh (3B translation models, 9 likes) — not notable. Partial entries rechecked: LLaDA2.2-flash (no official active-param count yet) and DeepSeek-V4-Flash-Vision-Exp (unchanged since Sep 1) stay partial; Step-5-Preview-BF16 still 401; LTX-2.5 + North-Small-Translate still gated."
    },
    {
      "date": "2026-09-25",
      "added": [],
      "upgraded": [],
      "note": "Checked — no changes. Discovery window Sep 24 09:37 → Sep 25 09:23: swept ~50 tracked orgs by lastModified, HF newest per pipeline (text-generation, image-text-to-text, text-to-image, text-to-video, image-to-video) since Sep 23, and trendingScore top-40. Everything found was out of atlas scope, a finetune/quant, or previously assessed: apple LensVLM-9B (192 likes, new — a visual-text-compression inference framework SFT+RL post-trained on the tracked Qwen3.5-9B backbone with an Expand(k) tool; architecture identical to Qwen3.5-9B + ViT, novelty is the post-training recipe, skip per no-finetune rule — same precedent as Intern-S2-397B); nvidia NV-Reason-CT (medical-CT 3D-VLM finetune on a qwen3_5 backbone, 1 like); alibabagroup SparkWan2.1/2.2 (sparsity-pruned Wan video quants); iknownuting Sulphur-2-base (LTX-2.3 quant); memset0 vsqa-preview (Wan2.1 DMD NVFP4 quant); alibaba-pai Qwen-Image-2.1-Fun Controlnet/LoRA adapters; AikidoSec altar-1 (GLM-5.3 AWQ int4 quant); Akhilaaa3 Jev-Omni (gemma-4-12B finetune, assessed Sep 15); plus previously skipped convaiinnovations laya (non-autoregressive router, out of scope), TaichuAI ZDTaichu5.0-9B, netease-youdao Confucius4-R2T2 (ASR), m-a-p YuE2-3B (music) & SheetSage2 (music transcription), internlm InternLumina-U2 (still a README-only placeholder), inclusionAI Ling/Ring 2.x refresh (org-wide repo touch, no new models), internlm Intern-S2-397B (assessed Sep 24), AlexWortega openjev, TencentARC GAE-D64-1B (assessed Sep 24). Closed API-only news out of scope. Partial rechecks: inclusionAI/LLaDA2.2-flash lastModified 2026-08-20 unchanged (still no official active-param count); deepseek-ai/DeepSeek-V4-Flash-Vision-Exp 2026-09-01 unchanged (~297B stays estimated); stepfun-ai/Step-5-Preview-BF16 still HTTP 401 (weights promised Oct 15); CohereLabs/North-Small-Translate-1.0 and Lightricks/LTX-2.5 raw configs still gated (26th run). No upgrades. 68 models unchanged, v28."
    },
    {
      "date": "2026-09-24",
      "added": [],
      "upgraded": [],
      "note": "Checked — no changes. Discovery window covered only Sep 23–24 (last run added Ming-Image-0.1-Design yesterday): swept ~45 tracked orgs by lastModified, HF newest per pipeline (text-generation, image-text-to-text, text-to-image, text-to-video, image-to-video) since Sep 22, trendingScore + likes7d top-40, and web search for Sep 23–24 announcements. Everything found was out of atlas scope or previously assessed: black-forest-labs FLUX-3-Action base/so101/droid (7B world-action model outputting robot joint targets — robotics policy, its text encoder is the tracked Qwen3-VL-4B); TencentARC GAE-D64-1B + WorldCrafter-Fast (camera-control video adapters, no tech report — consistent with the Sep-22 WorldCrafter skip); nvidia Nemotron-3-Diarization + sortformer family (speaker diarization, ASR-adjacent) and NVIDIA-NemotronLabs-VoiceChat-11B (speech, pre-dates window); moondream parakeet-ultra/redux (ASR); internlm Intern-S2-397B re-assessed after its Sep-22 README/deployment-guide refresh — still Qwen3_5MoeForConditionalGeneration on the tracked Qwen3.5-397B-A17B backbone (60L/d4096/512-expert-top-10 Gated-DeltaNet 3:1 hybrid, 403.4B BF16 per weight index), a Shanghai AI Lab scientific-agent post-train — skip per no-finetune rule; XiaomiMiMo MiMo-V2.6-Distill-Qwen-9B (distill of tracked family); AlexWortega/openjev (Qwen3.5-4B reranker finetune); Altworld Hemmingway-1 (Qwen3.8-27B creative finetune, skipped Sep 21); stealth-model space-bunny-alpha (README-only placeholder, no weights); Sep-24 text-generation feed was zero-like GGUF/ONNX/SFT churn. Closed API-only news (Claude Opus 5.5, GPT-6 Sol/Luna) remains out of scope. Partial rechecks: inclusionAI/LLaDA2.2-flash lastModified 2026-08-20 unchanged (still no official active-param count); deepseek-ai/DeepSeek-V4-Flash-Vision-Exp lastModified 2026-09-01 unchanged (~297B stays estimated); stepfun-ai/Step-5-Preview-BF16 still HTTP 401 (weights promised Oct 15); CohereLabs/North-Small-Translate-1.0 and Lightricks/LTX-2.5 raw configs still 401-gated (25th run). No upgrades. 68 models unchanged, v28."
    },
    {
      "date": "2026-09-23",
      "added": [
        "ming-image-0-1-design"
      ],
      "upgraded": [],
      "note": "Added Ming-Image-0.1-Design (Ant Group inclusionAI, MIT, weights live Sep 17/announced Sep 22, verified against transformer/config.json + mllm/config.json + weight index + GitHub modeling code): a 6B graphic-design text-to-image model (UI, infographics, posters) with native RGBA transparent output and strong in-image text rendering. Generation core is a 6.15B-BF16 single-stream flow-matching DiT (30 blocks, 30 heads × 128, d 3840, SwiGLU FFN 10240, QK-RMSNorm, 3-axis RoPE 32/48/48, adaLN-Zero scale+gate modulation, 2 extra refiner blocks, FlowMatchEuler shift 6.0); conditioning comes from a 17B BailingMM2 MoE-VLM (BailingMoeV2 20L/2048d, 256 experts top-8, sliding window 4096 + Qwen2.5-ViT + Qwen2 text encoder) projecting hidden states at layers 5/12/20 to 2560-d caption features. Companion Ming-Image-0.1-Design-Layer (same DiT, multi_frame_output) decomposes flat designs into RGBA layers and is noted on the card rather than tracked separately. Skipped: GPT-6 Sol/Luna and Claude Opus 5.5 (closed API-only, no weights), NVIDIA–Hugging Face acquisition (not a model), plus the usual finetune/quant churn (Bonsai-2 GGUF wave, Qwen-Image-2.1 quants/LoRAs, MiMo-V2.6 distills). Partial rechecks: LLaDA2.2-flash (Aug 20) and DeepSeek-V4-Flash-Vision-Exp (Sep 1) unchanged, stay partial; Step-5-Preview-BF16 still 401-gated, North-Small-Translate-1.0 and LTX-2.5 still gated (24th run). 68 models, v28."
    },
    {
      "date": "2026-09-22",
      "added": [
        "mimo-v2-6-pro-rl",
        "mimo-v2-6-flash-rl",
        "aliceai-foundation-80b-a3b"
      ],
      "upgraded": [],
      "note": "Added Xiaomi MiMo-V2.6-Pro-RL and MiMo-V2.6-Flash-RL (MIT, open-sourced Sep 21 with tech report; verified against config.json + weight index + modeling code): omnimodal (text/image/video/audio) sparse-MoE agent models at 1M context trained by one mixed-domain asynchronous GRPO run with Groupwise Agentic Grading (GRS rubrics + GAR advantage redistribution) toward recursive self-improvement — Pro 1.02T/42B (70L/6144d, 384 experts top-8) and Flash 309B/15B (48L/4096d, 256 experts top-8), both on a hybrid full-GQA + sliding-window-128 attention backbone (10+60 and 9+39 layers, learned attention-sink bias, d_h 192/v 128, partial rotary 0.334) with a dense first block, MXFP4-stored releases (566 GB / 172.9 GB), and a 5-layer non-causal DFlash speculative draft decoder (Flash also carries 3 MTP layers); recomputed totals match the official counts 1.00x. Also added Yandex AliceAI-Foundation-80B-A3B-Base (Apache-2.0, Sep 12, never previously assessed): a from-scratch 80B/3B base with a 12x(3 KDA linear + 1 gated-attention) hybrid layout, 512 tiny experts top-10+1 shared, 262K context, shipped with new Russian factuality benchmarks. Skipped: StepFun Step-5 Preview (API-only Sep 20; official HF repo still a 401 placeholder, weights promised Oct 15; the public Step-5-Preview-BF16 mirrors carry step3p5v/Step4 configs — not primary sources), XiaomiMiMo/MiMo-V2.6-Distill-Qwen-9B (distill), upstage solar-pro4-tokenizer (tokenizer only), nvidia/Kumo-Forecast (time-series, out of scope), TencentARC WorldCrafter (no tech report), plus quant/LoRA churn. Partial rechecks: LLaDA2.2-flash (Aug 20) and DeepSeek-V4-Flash-Vision-Exp (Sep 1) unchanged, stay partial; North-Small-Translate-1.0 and LTX-2.5 still 401-gated (23rd run). 67 models, v27."
    },
    {
      "date": "2026-09-21",
      "added": [
        "qwen-image-2-1"
      ],
      "upgraded": [],
      "note": "Added Qwen-Image-2.1 (Alibaba, Qwen Research License, verified against transformer/config.json, weight index, the diffusers implementation and the official blog): a 7B / 32-layer single-stream flow-matching DiT that unifies text-to-image generation and image editing in one model, with native RGBA transparency (absorbs Dec-2025's Qwen-Image-Layered) and up to 10 reference images. Architecturally notable for its mixed-granularity block-causal mask — token-level causal across the packed [text ; reference latents ; target latents] stream, bidirectional inside each image block — plus a single shared SiLU+Linear(4096→4×4096) modulation tensor sliced by every block and a prefix KV cache valid because text/reference tokens modulate from t=0. Conditioned by a Qwen3-VL encoder (36L/4096d + 27L/1152d ViT), 64-ch residual VAE, 3-axis RoPE 16/56/56. The HF repo sat as a placeholder since Sep 14 and the weights + blog went live Sep 20, which is why the Sep-20 run missed it. Skipped this run: Altworld/Hemmingway-1 (114 likes, base_model finetune of tracked Qwen3.8-27B), XGENlabs/XGEN-JING (finetune of tracked MiniMax-H3), Cactus-Compute/needle3 (121M on-device tool-calling model, not frontier), Qwen-Image-2.1-PE-T2I/I2I (prompt-rewriter companion models), plus GGUF/LoRA churn (Bonsai-2, Qwen-Image-2.1 quants). Partial rechecks: LLaDA2.2-flash (lastModified Aug 20) and DeepSeek-V4-Flash-Vision-Exp (Sep 1) unchanged, stay partial; North-Small-Translate-1.0 and LTX-2.5 still 401-gated (22nd run). 64 models, v26."
    },
    {
      "date": "2026-09-20",
      "added": [
        "realtime-venus-omni"
      ],
      "upgraded": [],
      "note": "Added Realtime-Venus-Omni (Ant Group inclusionAI + Tsinghua, arXiv 2609.13814, Apache-2.0, verified against config.json + README + safetensors index): a 9B full-duplex realtime interaction model on the MiniCPM-o 4.5 / Omni-Flow backbone — Qwen3-8B language decoder (36L/4096d GQA 32/8), SigLIP2 vision tower + 64-query resampler, Whisper-Medium audio encoder with pool-5 projection, and discrete S3 speech tokens decoded by a bundled 20-layer Token2wav streaming flow-matching head. First model in the atlas built around a shared causal timeline: it perceives video+audio continuously, decides per-second listen-vs-speak, and emits in-stream <delegate> events executed asynchronously by an external harness (dual-loop runtime) so tools never block the dialogue; training-free long-video memory retrieves archived audio-visual evidence. Beats Gemini 3.1 Live and GPT-4o on Full-Duplex-Bench v1.5 continuation metrics (97/88/86%). Skipped this run: ginigen-ai/Edge-4B-TELL (verbatim Gemma-4-E4B q4_0 GGUF mirror + 10KB linear confidence probe — derivative), BAAI/Brainmu-Spike (spike-camera conv LoRA, out of scope), nvidia DeepSeek-V4.1-Flash-NVFP4 (quant of tracked model), MiniMax-H3 LoRA/GGUF churn, Johnny-Z/Anima-Light-Lavender (finetune). Partial rechecks: LLaDA2.2-flash and DeepSeek-V4-Flash-Vision-Exp unchanged, stay partial; North-Small-Translate-1.0 and LTX-2.5 still 401-gated (21st run). 63 models, v25."
    },
    {
      "date": "2026-09-19",
      "added": [],
      "upgraded": [],
      "note": "Checked — no changes. Scanned HF newest-models (text-generation, image-text-to-text, text-to-image, text-to-video, image-to-video; createdAt ≥ Sep 17), a ~40-org sweep (DeepSeek, Qwen, zai-org, THUDM, moonshotai, meta, Mistral, google, nvidia, MiniMax, inclusionAI, internlm, BAAI, Agnes-AI, openbmb, nex-agi, m-a-p, TaichuAI, ibm-granite, Lightricks, et al.) and trending/likes top-40, plus web search for Sep 18–19 announcements. Everything new was derivative, out-of-scope, or already assessed: PrismML Bonsai 2 27B (926-like GGUF wave, Sep 18 press) remains a ternary quant of tracked Qwen3.8-27B per its base_model tag — 2nd consecutive skip; Local-Axiom-AI/Sabaki-Preview is a 0-like untrained GGUF research toy; akoumpa/Moonlight-V4-16B-A3B is an explicitly *untrained* architecture-only config (tags: untrained, architecture-config); convaiinnovations/laya is a non-autoregressive decision/router model (reinforcement-learning pipeline, no config.json) out of atlas scope; kpsss34/Walkyrie-7B-MoE is gated (401) and a finetune of its own 1.3B base; the text-to-image/video window was LoRA and quant churn only (Johnny-Z/Anima-Light-Lavender = circlestone-labs/Anima finetune; Jossbgo/Qwen-Image-2512 is a re-upload of the Dec 2025 Qwen official release; Ternary-Bonsai MLX/GGUF, FastH3 MLX, LTX-2.5 FP8, Wan2.2 GGUF re-uploads). Web search surfaced only closed-weight or platform news (Alibaba Qwen3.8-Omni-Flash is an API audio model with no open weights; Kimi K3 Bedrock GA and GitLab-hosted K3/M3/GLM-5.3 are distribution news for tracked models; nvidia Nemotron-3.5-Lightning-30B-A3B and Gemma-4 NVFP4 pages pre-date the window, Aug/Apr releases). Partial rechecks: inclusionAI/LLaDA2.2-flash README (lastModified Aug 20) still discloses no official active-param count and deepseek-v4-flash-vision-exp is unchanged (lastModified Sep 1) — both stay partial; CohereLabs/North-Small-Translate-1.0 and Lightricks/LTX-2.5 raw configs still gated HTTP 401 (20th run). No upgrades. 62 models unchanged."
    },
    {
      "date": "2026-09-18",
      "added": [
        "gigachat3-5-reasoning",
        "xing4-0-29b-a4b"
      ],
      "upgraded": [],
      "note": "Added two open-weight frontier-class MoEs verified against HF config.json + README: GigaChat 3.5 Reasoning (Sber, 432B/28B, MIT — 256-expert top-8 + 1 shared over 30 GatedDeltaNet / 10 gated-MLA hybrid layers, ZeroCenteredGatedNorm pre+post, 3 MTP heads, six domain experts merged by online-RL + on-policy distillation, natively FP8-trained) and Xing4.0-29B-A4B (China Telecom, TeleChat lineage, 29B/4B Apache-2.0 — all-MLA MoE with 4-stream mHC hyper-connected residuals, 1 MTP draft layer, first model of its scale trained end-to-end on Ascend NPUs). Skipped as derivatives: prism-ml Ternary-Bonsai-2-27B (ternary quant of tracked Qwen3.8-27B per base_model tag), nvidia DeepSeek-V4.1-Flash-NVFP4, ZGCM-1-7B (small dense, no novelty). 62 models, v24."
    },
    {
      "date": "2026-09-17",
      "added": [],
      "upgraded": [],
      "note": "Checked — no changes. Scanned HF newest-models (text-generation, image-text-to-text, text-to-image, text-to-video, image-to-video; createdAt ≥ Sep 15), ~40-org sweep (DeepSeek, Qwen, zai-org, THUDM, moonshotai, meta, Mistral, google, nvidia, MiniMax, inclusionAI, internlm, BAAI, Agnes-AI, openbmb, nex-agi, m-a-p, TaichuAI, ibm-granite, Lightricks, et al.), trendingScore + likes7d top-40, and web search. Everything new since the last run was a derivative or re-upload of tracked/previously-assessed models: empero-ai/Qwen3.8-35B-A3B-Distill (12 likes) is an SFT distillation of tracked Qwen3.6-35B-A3B per its base_model tag — no-distill rule; harshatheg/Qwen-2.5-1B-RLCD (127 likes) is an MLX constrained-decoding finetune of Qwen2.5-1.5B-Instruct; CrowtherLabs/atom-proton-1.0 and Mapika/decider-2b-vision are Qwen3.8-27B-FP8 / Qwen3.5-2B finetunes; x-square-robot/X-Planner-9B and keepstar/Kali-Lite-Vision-9B are qwen3_5-arch domain VLMs; BAAI/Brainmu-Spike is a spike-camera reconstruction LoRA (out of atlas scope); internlm/Atria-Dawn-Preview-Ascend-w8a8 is a quant of the Sep-15-skipped Atria (config-identical to tracked GLM-5.2); PrismLive-2B/4B are MLX quants of gemma-4-E4B; TaichuAI/ZDTaichu5.0-9B-FP8/MLX/GGUF are quants of the already-assessed Sep-4 9B; plus the usual luganoquant/kingjones777/comatto/Abiray quant-GGUF wave over DeepSeek-V4.1-Flash, GLM-5.3-Flash, Kimi-K3, Agnes-3.0-Flash, Qwen3.8-Flash-Next, LTX-2.5, MiniMax-H3 and Wan2.2, the frtertaer LTX-2.5-uncensored FP8 re-upload, FastVideo-FastH3 LoRAs, and SDXL/Flux/Krea/Z-Image LoRA churn. Web search surfaced only closed-weight or derivative items (Abacus Smaug = Kimi-K3/V4-Flash/Qwen3.8-27B post-trains; State-of-Open-Source report mentions no new open weights). Partial rechecks: llada2-2-flash README still discloses no official active-param count (lastModified Aug 20) and deepseek-v4-flash-vision-exp is unchanged (lastModified Sep 1) — both stay partial; CohereLabs/North-Small-Translate-1.0 and Lightricks/LTX-2.5 still gated HTTP 401 (18th run). 60 models unchanged."
    }
  ]
};
