window.MODELS = [
{
"id": "glm-4-5",
"name": "GLM-4.5",
"org": "Zhipu",
"family": "GLM",
"released": "2025-07",
"license": "MIT",
"modality": "text",
"decoder_type": "MoE",
"params_total_B": 355,
"params_active_B": 32,
"n_layers": 92,
"d_model": 5120,
"d_ff": 12288,
"d_ff_moe": 1536,
"n_heads": 96,
"n_kv_heads": 8,
"head_dim": 128,
"attention": "GQA",
"attention_detail": "GQA 96 Q / 8 KV heads, head_dim 128, QK-norm, attention bias, partial RoPE (0.5).",
"n_experts": 160,
"active_experts": 8,
"shared_experts": 1,
"vocab_size": 151552,
"context_length": 131072,
"norm": "RMSNorm",
"norm_placement": "pre",
"pos_encoding": "partial-RoPE",
"activation": "SwiGLU",
"tie_embeddings": false,
"vision": null,
"notes": "355B/32B MoE with first 3 dense layers then 160 routed experts (top-8) + 1 shared; QK-norm and partial (50%) RoPE; includes an MTP layer.",
"sources": [
"https://huggingface.co/zai-org/GLM-4.5"
],
"confidence": "verified"
},
{
"id": "glm-4-6",
"name": "GLM-4.6",
"org": "Zhipu",
"family": "GLM",
"released": "2025-09",
"license": "MIT",
"modality": "text",
"decoder_type": "MoE",
"params_total_B": 355,
"params_active_B": 32,
"n_layers": 92,
"d_model": 5120,
"d_ff": 12288,
"d_ff_moe": 1536,
"n_heads": 96,
"n_kv_heads": 8,
"head_dim": 128,
"attention": "GQA",
"attention_detail": "GQA 96 Q / 8 KV heads, head_dim 128, QK-norm, attention bias, partial RoPE (0.5).",
"n_experts": 160,
"active_experts": 8,
"shared_experts": 1,
"vocab_size": 151552,
"context_length": 202752,
"norm": "RMSNorm",
"norm_placement": "pre",
"pos_encoding": "partial-RoPE",
"activation": "SwiGLU",
"tie_embeddings": false,
"vision": null,
"notes": "Architecturally identical to GLM-4.5 but extends native context to ~200K; 160 routed experts top-8 + 1 shared.",
"sources": [
"https://huggingface.co/zai-org/GLM-4.6"
],
"confidence": "verified"
},
{
"id": "kimi-k2",
"name": "Kimi K2",
"org": "Moonshot",
"family": "Kimi",
"released": "2025-07",
"license": "Modified MIT",
"modality": "text",
"decoder_type": "MoE",
"params_total_B": 1000,
"params_active_B": 32,
"n_layers": 61,
"d_model": 7168,
"d_ff": 18432,
"d_ff_moe": 2048,
"n_heads": 64,
"n_kv_heads": 64,
"head_dim": 192,
"attention": "MLA",
"attention_detail": "DeepSeek-V3 MLA: kv_lora_rank 512, q_lora_rank 1536, qk_nope 128 + qk_rope 64, v_head_dim 128; 64 heads; YaRN to 128K.",
"n_experts": 384,
"active_experts": 8,
"shared_experts": 1,
"vocab_size": 163840,
"context_length": 131072,
"norm": "RMSNorm",
"norm_placement": "pre",
"pos_encoding": "RoPE",
"activation": "SwiGLU",
"tie_embeddings": false,
"vision": null,
"notes": "1T/32B MoE reusing DeepSeek-V3's MLA architecture but scaled to 384 routed experts (top-8) + 1 shared and only 1 dense layer; trained with the MuonClip optimizer for stability. Ships FP8.",
"sources": [
"https://huggingface.co/moonshotai/Kimi-K2-Instruct"
],
"confidence": "verified"
},
{
"id": "minimax-m2",
"name": "MiniMax-M2",
"org": "MiniMax",
"family": "MiniMax",
"released": "2025-10",
"license": "MIT",
"modality": "text",
"decoder_type": "MoE",
"params_total_B": 230,
"params_active_B": 10,
"n_layers": 62,
"d_model": 3072,
"d_ff": 8192,
"d_ff_moe": 1536,
"n_heads": 48,
"n_kv_heads": 8,
"head_dim": 128,
"attention": "GQA",
"attention_detail": "Full softmax GQA 48 Q / 8 KV heads (no lightning attention, unlike M1/Text-01), QK-norm, partial RoPE (rotary_dim 64).",
"n_experts": 256,
"active_experts": 8,
"shared_experts": 0,
"vocab_size": 200064,
"context_length": 196608,
"norm": "RMSNorm",
"norm_placement": "pre",
"pos_encoding": "partial-RoPE",
"activation": "SwiGLU",
"tie_embeddings": false,
"vision": null,
"notes": "~230B/10B MoE with 256 experts (top-8), tuned for agentic/coding. Unlike MiniMax-Text-01/M1, M2 uses full softmax attention throughout (dropped the linear-attention hybrid).",
"sources": [
"https://huggingface.co/MiniMaxAI/MiniMax-M2"
],
"confidence": "verified"
},
{
"id": "minimax-text-01",
"name": "MiniMax-Text-01",
"org": "MiniMax",
"family": "MiniMax",
"released": "2025-01",
"license": "MiniMax Model License",
"modality": "text",
"decoder_type": "MoE",
"params_total_B": 456,
"params_active_B": 45.9,
"n_layers": 80,
"d_model": 6144,
"d_ff": 9216,
"d_ff_moe": 9216,
"n_heads": 64,
"n_kv_heads": 8,
"head_dim": 128,
"attention": "hybrid",
"attention_detail": "Lightning (linear) attention in 7 of every 8 layers + 1 softmax GQA layer (7:1); softmax layers use partial RoPE (rotary_dim 64).",
"n_experts": 32,
"active_experts": 2,
"shared_experts": 0,
"vocab_size": 200064,
"context_length": 10240000,
"norm": "RMSNorm",
"norm_placement": "post",
"pos_encoding": "partial-RoPE",
"activation": "SwiGLU",
"tie_embeddings": false,
"vision": null,
"notes": "456B/45.9B MoE (32 experts, top-2). Hybrid attention: lightning linear attention on 7/8 layers with a full softmax layer every 8th; postnorm placement; extrapolates to 10M+ context.",
"sources": [
"https://huggingface.co/MiniMaxAI/MiniMax-Text-01",
"https://arxiv.org/pdf/2501.08313"
],
"confidence": "verified"
},
{
"id": "gemma-3-27b",
"name": "Gemma 3 27B",
"org": "Google",
"family": "Gemma",
"released": "2025-03",
"license": "Gemma",
"modality": "multimodal",
"decoder_type": "Dense",
"params_total_B": 27,
"params_active_B": 27,
"n_layers": 62,
"d_model": 5376,
"d_ff": 21504,
"d_ff_moe": null,
"n_heads": 32,
"n_kv_heads": 16,
"head_dim": 128,
"attention": "hybrid",
"attention_detail": "GQA 32 Q / 16 KV heads with QK-norm; 5 local sliding-window (1024) layers per 1 global layer; local RoPE base 10K, global RoPE base 1M.",
"n_experts": null,
"active_experts": null,
"shared_experts": null,
"vocab_size": 262208,
"context_length": 131072,
"norm": "RMSNorm",
"norm_placement": "sandwich",
"pos_encoding": "RoPE",
"activation": "GeGLU",
"tie_embeddings": true,
"vision": {
"encoder": "SigLIP-So400m",
"encoder_params_B": 0.4,
"fusion": "adapter",
"notes": "SigLIP-So400m encoder (896x896 image); 256 tokens/image via a mean-pool projector into the LM."
},
"notes": "Dense 27B LM with interleaved 5:1 local:global attention (local sliding window 1024) to cut KV-cache cost, QK-norm, GeGLU MLP, and sandwich (pre+post) RMSNorm around each block. Multimodal via a SigLIP encoder.",
"sources": [
"https://huggingface.co/google/gemma-3-27b-it",
"https://arxiv.org/html/2503.19786v1"
],
"confidence": "verified"
},
{
"id": "ernie-4-5-300b-a47b",
"name": "ERNIE 4.5 300B-A47B",
"org": "Baidu",
"family": "ERNIE",
"released": "2025-06",
"license": "Apache-2.0",
"modality": "text",
"decoder_type": "MoE",
"params_total_B": 300,
"params_active_B": 47,
"n_layers": 54,
"d_model": 8192,
"d_ff": 28672,
"d_ff_moe": 3584,
"n_heads": 64,
"n_kv_heads": 8,
"head_dim": 128,
"attention": "GQA",
"attention_detail": "GQA 64 Q / 8 KV heads, head_dim 128; FlashMask dynamic attention masking; RoPE theta 500K.",
"n_experts": 64,
"active_experts": 8,
"shared_experts": 0,
"vocab_size": 103424,
"context_length": 131072,
"norm": "RMSNorm",
"norm_placement": "pre",
"pos_encoding": "RoPE",
"activation": "SwiGLU",
"tie_embeddings": false,
"vision": null,
"notes": "300B/47B text MoE (64 routed experts, top-8, no shared); first 3 layers dense. Text portion of Baidu's heterogeneous-MoE ERNIE 4.5 (full multimodal model ~424B); includes an MTP layer.",
"sources": [
"https://huggingface.co/baidu/ERNIE-4.5-300B-A47B-PT",
"https://ernie.baidu.com/blog/publication/ERNIE_Technical_Report.pdf"
],
"confidence": "verified"
},
{
"id": "glm-5-2",
"name": "GLM-5.2",
"org": "Zhipu",
"family": "GLM",
"released": "2026-06",
"license": "MIT",
"modality": "text",
"decoder_type": "MoE",
"params_total_B": 744,
"params_active_B": 40,
"n_layers": 78,
"d_model": 6144,
"d_ff": 12288,
"d_ff_moe": 2048,
"n_heads": 64,
"n_kv_heads": 64,
"head_dim": 256,
"attention": "sparse",
"attention_detail": "DeepSeek-style MLA + DSA sparse attention (index_topk 2048); q_lora 2048, kv_lora 512, qk_nope 192 + qk_rope 64 = 256, v 256.",
"n_experts": 256,
"active_experts": 8,
"shared_experts": 1,
"vocab_size": 151552,
"context_length": 1048576,
"norm": "RMSNorm",
"norm_placement": "pre",
"pos_encoding": "partial-RoPE",
"activation": "SwiGLU",
"tie_embeddings": false,
"vision": null,
"notes": "GLM-5.2 moves the GLM line from GQA to DeepSeek-style MLA + DSA sparse attention (top-2048 keys) — the shift that enables its 1M-token context; 744B/40B, 256 experts top-8 + 1 shared.",
"sources": [
"https://huggingface.co/zai-org/GLM-5.2"
],
"confidence": "verified"
},
{
"id": "kimi-k2-7",
"name": "Kimi K2.7",
"org": "Moonshot",
"family": "Kimi",
"released": "2026-06",
"license": "Modified MIT",
"modality": "multimodal",
"decoder_type": "MoE",
"params_total_B": 1000,
"params_active_B": 32,
"n_layers": 61,
"d_model": 7168,
"d_ff": 18432,
"d_ff_moe": 2048,
"n_heads": 64,
"n_kv_heads": 64,
"head_dim": 192,
"attention": "MLA",
"attention_detail": "DeepSeek-V3-style MLA (kv_lora 512, q_lora 1536, qk 192, v 128); full attention.",
"n_experts": 384,
"active_experts": 8,
"shared_experts": 1,
"vocab_size": 163840,
"context_length": 262144,
"norm": "RMSNorm",
"norm_placement": "pre",
"pos_encoding": "RoPE",
"activation": "SwiGLU",
"tie_embeddings": false,
"vision": {
"encoder": "MoonViT",
"encoder_params_B": 0.4,
"fusion": "adapter",
"notes": "400M MoonViT vision encoder for native multimodal input."
},
"notes": "Kimi K2.7-Code: 1T/32B MoE on the DeepSeek-V3 MLA backbone (61 layers, 384 experts top-8 + 1 shared), now multimodal via a 400M MoonViT encoder; 256K context.",
"sources": [
"https://www.kimi.com/resources/kimi-k2-7-code"
],
"confidence": "partial"
},
{
"id": "llama-3-3-70b",
"name": "Llama 3.3 70B",
"org": "Meta",
"family": "Llama",
"released": "2024-12",
"license": "Llama 3.3 Community",
"modality": "text",
"decoder_type": "Dense",
"params_total_B": 70,
"params_active_B": 70,
"n_layers": 80,
"d_model": 8192,
"d_ff": 28672,
"d_ff_moe": null,
"n_heads": 64,
"n_kv_heads": 8,
"head_dim": 128,
"attention": "GQA",
"attention_detail": "Full attention, GQA 64 query / 8 KV heads; RoPE theta 500000 with Llama3 rope-scaling (factor 8) for 128K context.",
"n_experts": null,
"active_experts": null,
"shared_experts": null,
"vocab_size": 128256,
"context_length": 131072,
"norm": "RMSNorm",
"norm_placement": "pre",
"pos_encoding": "RoPE",
"activation": "SwiGLU",
"tie_embeddings": false,
"vision": null,
"notes": "Dense 70B decoder, architecturally identical to Llama 3.1 70B; instruction-tuned refresh reaching ~405B-class quality. GQA with 8 KV heads, 128K context.",
"sources": [
"https://huggingface.co/meta-llama/Llama-3.3-70B-Instruct"
],
"confidence": "verified"
},
{
"id": "llama-4-scout",
"name": "Llama 4 Scout (17B-16E)",
"org": "Meta",
"family": "Llama",
"released": "2025-04",
"license": "Llama 4 Community",
"modality": "multimodal",
"decoder_type": "MoE",
"params_total_B": 109,
"params_active_B": 17,
"n_layers": 48,
"d_model": 5120,
"d_ff": 16384,
"d_ff_moe": 8192,
"n_heads": 40,
"n_kv_heads": 8,
"head_dim": 128,
"attention": "hybrid",
"attention_detail": "iRoPE: interleaved chunked local attention (chunk 8192) with global NoPE layers every 4th layer; QK-norm on RoPE layers; GQA 40/8; temperature-scaled attention for extrapolation to 10M context.",
"n_experts": 16,
"active_experts": 1,
"shared_experts": 1,
"vocab_size": 202048,
"context_length": 10485760,
"norm": "RMSNorm",
"norm_placement": "pre",
"pos_encoding": "iRoPE",
"activation": "SwiGLU",
"tie_embeddings": false,
"vision": {
"encoder": "MetaCLIP (native early-fusion)",
"encoder_params_B": null,
"fusion": "early-fusion",
"notes": "Native multimodal via early fusion of vision tokens into the decoder."
},
"notes": "MoE with 16 routed experts (top-1) plus 1 always-on shared expert in every layer; native multimodal early fusion; iRoPE (RoPE + periodic NoPE layers) enables a 10M-token context. Fits one H100 at int4.",
"sources": [
"https://huggingface.co/meta-llama/Llama-4-Scout-17B-16E-Instruct",
"https://ai.meta.com/blog/llama-4-multimodal-intelligence/"
],
"confidence": "verified"
},
{
"id": "llama-4-maverick",
"name": "Llama 4 Maverick (17B-128E)",
"org": "Meta",
"family": "Llama",
"released": "2025-04",
"license": "Llama 4 Community",
"modality": "multimodal",
"decoder_type": "MoE",
"params_total_B": 400,
"params_active_B": 17,
"n_layers": 48,
"d_model": 5120,
"d_ff": 16384,
"d_ff_moe": 8192,
"n_heads": 40,
"n_kv_heads": 8,
"head_dim": 128,
"attention": "hybrid",
"attention_detail": "iRoPE: chunked local attention (chunk 8192) interleaved with global NoPE layers every 4th layer; GQA 40/8; no QK-norm. MoE alternates with dense layers (interleave step 2).",
"n_experts": 128,
"active_experts": 1,
"shared_experts": 1,
"vocab_size": 202048,
"context_length": 1048576,
"norm": "RMSNorm",
"norm_placement": "pre",
"pos_encoding": "iRoPE",
"activation": "SwiGLU",
"tie_embeddings": false,
"vision": {
"encoder": "MetaCLIP (native early-fusion)",
"encoder_params_B": null,
"fusion": "early-fusion",
"notes": "Native multimodal early fusion."
},
"notes": "128 routed experts (top-1) plus 1 shared expert, with MoE layers alternating with dense FFN layers; 17B active of ~400B total; native multimodal; 1M-token context.",
"sources": [
"https://huggingface.co/meta-llama/Llama-4-Maverick-17B-128E-Instruct",
"https://ai.meta.com/blog/llama-4-multimodal-intelligence/"
],
"confidence": "verified"
},
{
"id": "mistral-small-3-1-24b",
"name": "Mistral Small 3.1 24B",
"org": "Mistral AI",
"family": "Mistral",
"released": "2025-03",
"license": "Apache-2.0",
"modality": "multimodal",
"decoder_type": "Dense",
"params_total_B": 24,
"params_active_B": 24,
"n_layers": 40,
"d_model": 5120,
"d_ff": 32768,
"d_ff_moe": null,
"n_heads": 32,
"n_kv_heads": 8,
"head_dim": 128,
"attention": "GQA",
"attention_detail": "Full (dense) attention, no sliding window; GQA 32 query / 8 KV heads; RoPE theta 1e9 for 128K context.",
"n_experts": null,
"active_experts": null,
"shared_experts": null,
"vocab_size": 131072,
"context_length": 131072,
"norm": "RMSNorm",
"norm_placement": "pre",
"pos_encoding": "RoPE",
"activation": "SwiGLU",
"tie_embeddings": false,
"vision": {
"encoder": "Pixtral ViT",
"encoder_params_B": 0.4,
"fusion": "adapter",
"notes": "Pixtral vision encoder for native multimodality."
},
"notes": "Dense 24B decoder with large RoPE theta (1e9) and no sliding window (unlike earlier Mistral); adds a Pixtral vision encoder. 128K context, Apache-2.0.",
"sources": [
"https://huggingface.co/mistralai/Mistral-Small-3.1-24B-Instruct-2503"
],
"confidence": "verified"
},
{
"id": "mixtral-8x22b",
"name": "Mixtral 8x22B",
"org": "Mistral AI",
"family": "Mixtral",
"released": "2024-04",
"license": "Apache-2.0",
"modality": "text",
"decoder_type": "MoE",
"params_total_B": 141,
"params_active_B": 39,
"n_layers": 56,
"d_model": 6144,
"d_ff": null,
"d_ff_moe": 16384,
"n_heads": 48,
"n_kv_heads": 8,
"head_dim": 128,
"attention": "GQA",
"attention_detail": "Full attention, GQA 48 query / 8 KV heads; RoPE theta 1e6; no sliding window in this release.",
"n_experts": 8,
"active_experts": 2,
"shared_experts": null,
"vocab_size": 32768,
"context_length": 65536,
"norm": "RMSNorm",
"norm_placement": "pre",
"pos_encoding": "RoPE",
"activation": "SwiGLU",
"tie_embeddings": false,
"vision": null,
"notes": "Classic sparse MoE: 8 experts per FFN, top-2 routed, no shared expert; 141B total / ~39B active. 64K context, 32K vocab. The reference open MoE.",
"sources": [
"https://huggingface.co/mistralai/Mixtral-8x22B-Instruct-v0.1",
"https://mistral.ai/news/mixtral-8x22b/"
],
"confidence": "verified"
},
{
"id": "gpt-oss-120b",
"name": "gpt-oss-120b",
"org": "OpenAI",
"family": "gpt-oss",
"released": "2025-08",
"license": "Apache-2.0",
"modality": "text",
"decoder_type": "MoE",
"params_total_B": 117,
"params_active_B": 5.1,
"n_layers": 36,
"d_model": 2880,
"d_ff": null,
"d_ff_moe": 2880,
"n_heads": 64,
"n_kv_heads": 8,
"head_dim": 64,
"attention": "hybrid",
"attention_detail": "Alternating banded sliding-window (window 128) and full attention layers; learned per-head attention sinks; GQA 64/8; YaRN RoPE (theta 150000, factor 32) to 131K.",
"n_experts": 128,
"active_experts": 4,
"shared_experts": null,
"vocab_size": 201088,
"context_length": 131072,
"norm": "RMSNorm",
"norm_placement": "pre",
"pos_encoding": "RoPE",
"activation": "SwiGLU",
"tie_embeddings": false,
"vision": null,
"notes": "OpenAI's open-weight MoE: 128 experts (top-4), MXFP4-quantized expert weights (~63GB, fits one 80GB GPU); sliding-window+full attention alternation with learned attention sinks; clipped SwiGLU. 5.1B active / 117B total.",
"sources": [
"https://huggingface.co/openai/gpt-oss-120b",
"https://openai.com/index/introducing-gpt-oss/"
],
"confidence": "verified"
},
{
"id": "gpt-oss-20b",
"name": "gpt-oss-20b",
"org": "OpenAI",
"family": "gpt-oss",
"released": "2025-08",
"license": "Apache-2.0",
"modality": "text",
"decoder_type": "MoE",
"params_total_B": 21,
"params_active_B": 3.6,
"n_layers": 24,
"d_model": 2880,
"d_ff": null,
"d_ff_moe": 2880,
"n_heads": 64,
"n_kv_heads": 8,
"head_dim": 64,
"attention": "hybrid",
"attention_detail": "Alternating banded sliding-window (window 128) and full attention; learned per-head attention sinks; GQA 64/8; YaRN RoPE to 131K.",
"n_experts": 32,
"active_experts": 4,
"shared_experts": null,
"vocab_size": 201088,
"context_length": 131072,
"norm": "RMSNorm",
"norm_placement": "pre",
"pos_encoding": "RoPE",
"activation": "SwiGLU",
"tie_embeddings": false,
"vision": null,
"notes": "Smaller gpt-oss with 32 experts (top-4), MXFP4-quantized experts fitting ~16GB; same sliding-window+full alternation with attention sinks and clipped SwiGLU. 3.6B active / 21B total.",
"sources": [
"https://huggingface.co/openai/gpt-oss-20b",
"https://openai.com/index/introducing-gpt-oss/"
],
"confidence": "verified"
},
{
"id": "qwen2.5-vl-72b",
"name": "Qwen2.5-VL-72B",
"org": "Alibaba",
"family": "Qwen2.5-VL",
"released": "2025-01",
"license": "Qwen License",
"modality": "multimodal",
"decoder_type": "Dense",
"params_total_B": 73,
"params_active_B": 73,
"n_layers": 80,
"d_model": 8192,
"d_ff": 29568,
"d_ff_moe": null,
"n_heads": 64,
"n_kv_heads": 8,
"head_dim": 128,
"attention": "GQA",
"attention_detail": "GQA 64 query / 8 KV heads; full attention (sliding window disabled). M-RoPE for video/time alignment.",
"n_experts": null,
"active_experts": null,
"shared_experts": null,
"vocab_size": 152064,
"context_length": 128000,
"norm": "RMSNorm",
"norm_placement": "pre",
"pos_encoding": "2D-RoPE",
"activation": "SwiGLU",
"tie_embeddings": false,
"vision": {
"encoder": "Native-dynamic-resolution ViT (depth 32, hidden 1280)",
"encoder_params_B": 0.675,
"fusion": "adapter",
"notes": "From-scratch ViT with window attention (window 112) + full attention at 4 layers; MLP patch-merger (2x2 -> 8192); 2D-RoPE; native dynamic resolution."
},
"notes": "Dense 72B Qwen2.5 LLM + from-scratch native-dynamic-resolution ViT with window attention for near-linear visual scaling; M-RoPE adds absolute-time/video alignment.",
"sources": [
"https://huggingface.co/Qwen/Qwen2.5-VL-72B-Instruct",
"https://arxiv.org/abs/2502.13923"
],
"confidence": "verified"
},
{
"id": "qwen3-vl-235b-a22b",
"name": "Qwen3-VL-235B-A22B",
"org": "Alibaba",
"family": "Qwen3-VL",
"released": "2025-09",
"license": "Apache-2.0",
"modality": "multimodal",
"decoder_type": "MoE",
"params_total_B": 235,
"params_active_B": 22,
"n_layers": 94,
"d_model": 4096,
"d_ff": 12288,
"d_ff_moe": 1536,
"n_heads": 64,
"n_kv_heads": 4,
"head_dim": 128,
"attention": "GQA",
"attention_detail": "GQA 64 query / 4 KV heads, head_dim 128 (decoupled); Interleaved-MRoPE, rope_theta 5e6.",
"n_experts": 128,
"active_experts": 8,
"shared_experts": 0,
"vocab_size": 151936,
"context_length": 262144,
"norm": "RMSNorm",
"norm_placement": "pre",
"pos_encoding": "2D-RoPE",
"activation": "SwiGLU",
"tie_embeddings": false,
"vision": {
"encoder": "Redesigned ViT (depth 27, hidden 1152)",
"encoder_params_B": 0.65,
"fusion": "adapter",
"notes": "MLP merger (2x2) + DeepStack: multi-level ViT features injected at LLM layers 8/16/24; native dynamic resolution."
},
"notes": "Qwen3-235B-A22B MoE backbone (128 experts / 8 active, no shared) fused with a ViT via DeepStack multi-level feature injection and Interleaved-MRoPE; 256K native context extendable to 1M.",
"sources": [
"https://huggingface.co/Qwen/Qwen3-VL-235B-A22B-Instruct",
"https://arxiv.org/abs/2511.21631"
],
"confidence": "verified"
},
{
"id": "internvl3-78b",
"name": "InternVL3-78B",
"org": "OpenGVLab",
"family": "InternVL3",
"released": "2025-04",
"license": "Qwen License",
"modality": "multimodal",
"decoder_type": "Dense",
"params_total_B": 78,
"params_active_B": 78,
"n_layers": 80,
"d_model": 8192,
"d_ff": 29568,
"d_ff_moe": null,
"n_heads": 64,
"n_kv_heads": 8,
"head_dim": 128,
"attention": "GQA",
"attention_detail": "GQA 64 query / 8 KV heads, head_dim 128; RoPE theta 1e6 with dynamic-NTK scaling.",
"n_experts": null,
"active_experts": null,
"shared_experts": null,
"vocab_size": 151674,
"context_length": 32768,
"norm": "RMSNorm",
"norm_placement": "pre",
"pos_encoding": "RoPE",
"activation": "SwiGLU",
"tie_embeddings": false,
"vision": {
"encoder": "InternViT-6B-448px (depth 45, hidden 3200, QK-norm)",
"encoder_params_B": 6.0,
"fusion": "adapter",
"notes": "ViT-MLP-LLM; pixel-shuffle downsampling cuts visual tokens to 1/4, MLP projector to 8192; dynamic 448px tiling (1-12 tiles + thumbnail)."
},
"notes": "Dense InternViT-6B encoder + Qwen2.5-72B LLM via an MLP projector; adds Native Multimodal Pre-Training and Variable Visual Position Encoding (V2PE). ~78B total = 6B ViT + 72B LLM.",
"sources": [
"https://huggingface.co/OpenGVLab/InternVL3-78B",
"https://arxiv.org/abs/2504.10479"
],
"confidence": "verified"
},
{
"id": "kimi-vl-a3b",
"name": "Kimi-VL-A3B",
"org": "Moonshot",
"family": "Kimi-VL",
"released": "2025-04",
"license": "MIT",
"modality": "multimodal",
"decoder_type": "MoE",
"params_total_B": 16,
"params_active_B": 2.8,
"n_layers": 27,
"d_model": 2048,
"d_ff": 11264,
"d_ff_moe": 1408,
"n_heads": 16,
"n_kv_heads": 16,
"head_dim": 192,
"attention": "MLA",
"attention_detail": "MLA (DeepSeek-V3 style): kv_lora_rank 512, decoupled RoPE qk_nope 128 + qk_rope 64 (=192), v_head_dim 128.",
"n_experts": 64,
"active_experts": 6,
"shared_experts": 2,
"vocab_size": 163840,
"context_length": 131072,
"norm": "RMSNorm",
"norm_placement": "pre",
"pos_encoding": "RoPE",
"activation": "SwiGLU",
"tie_embeddings": false,
"vision": {
"encoder": "MoonViT (SigLIP-SO400M init; depth 27, hidden 1152)",
"encoder_params_B": 0.4,
"fusion": "adapter",
"notes": "Native-resolution encoder (no tiling), 2x2 spatial merge then MLP projector into 2048-dim LLM space."
},
"notes": "Efficient MoE VLM: MoonViT + MLP projector feeding a Moonlight-16B-A3B DeepSeek-V3-style MoE LLM (MLA, aux-loss-free routing, 64 routed + 2 shared, 6 active); ~2.8B active of 16B, 128K context.",
"sources": [
"https://huggingface.co/moonshotai/Kimi-VL-A3B-Instruct",
"https://arxiv.org/abs/2504.07491"
],
"confidence": "verified"
},
{
"id": "gpt2-xl",
"name": "GPT-2 XL",
"org": "OpenAI",
"family": "GPT-2",
"released": "2019-11",
"license": "MIT",
"modality": "text",
"decoder_type": "Dense",
"params_total_B": 1.5,
"params_active_B": 1.5,
"n_layers": 48,
"d_model": 1600,
"d_ff": 6400,
"d_ff_moe": null,
"n_heads": 25,
"n_kv_heads": 25,
"head_dim": 64,
"attention": "MHA",
"attention_detail": "Standard multi-head causal self-attention, 25 heads x 64 dim; no GQA/MQA.",
"n_experts": null,
"active_experts": null,
"shared_experts": null,
"vocab_size": 50257,
"context_length": 1024,
"norm": "LayerNorm",
"norm_placement": "pre",
"pos_encoding": "learned",
"activation": "GeLU",
"tie_embeddings": true,
"vision": null,
"notes": "Historical anchor: largest GPT-2 (1.5B). Popularized pre-normalization + an extra final LayerNorm, learned absolute positional embeddings, and tied input/output embeddings (tanh-approx GeLU).",
"sources": [
"https://huggingface.co/openai-community/gpt2-xl",
"https://cdn.openai.com/better-language-models/language_models_are_unsupervised_multitask_learners.pdf"
],
"confidence": "verified"
},
{
"id": "llama-2-70b",
"name": "Llama 2 70B",
"org": "Meta",
"family": "Llama 2",
"released": "2023-07",
"license": "Llama 2 Community",
"modality": "text",
"decoder_type": "Dense",
"params_total_B": 70,
"params_active_B": 70,
"n_layers": 80,
"d_model": 8192,
"d_ff": 28672,
"d_ff_moe": null,
"n_heads": 64,
"n_kv_heads": 8,
"head_dim": 128,
"attention": "GQA",
"attention_detail": "Grouped-query attention, 64 query heads sharing 8 KV heads, head_dim 128; ~8x smaller KV cache vs MHA.",
"n_experts": null,
"active_experts": null,
"shared_experts": null,
"vocab_size": 32000,
"context_length": 4096,
"norm": "RMSNorm",
"norm_placement": "pre",
"pos_encoding": "RoPE",
"activation": "SwiGLU",
"tie_embeddings": false,
"vision": null,
"notes": "The GQA anchor: GQA applied to 34B/70B sizes (smaller Llama 2 use MHA). Pre-norm RMSNorm + RoPE + SwiGLU with ~2/3 scaling.",
"sources": [
"https://huggingface.co/meta-llama/Llama-2-70b-hf",
"https://arxiv.org/abs/2307.09288"
],
"confidence": "verified"
},
{
"id": "flux1-dev",
"name": "FLUX.1 [dev]",
"org": "Black Forest Labs",
"family": "FLUX.1",
"released": "2024-08",
"license": "FLUX.1 [dev] Non-Commercial",
"modality": "image-gen",
"decoder_type": "DiT (diffusion transformer)",
"params_total_B": 12,
"params_active_B": 12,
"n_layers": 57,
"d_model": 3072,
"d_ff": 12288,
"d_ff_moe": null,
"n_heads": 24,
"n_kv_heads": null,
"head_dim": 128,
"attention": "MMDiT",
"attention_detail": "19 double-stream (MMDiT, joint text+image attention with separate modulation) + 38 single-stream (unified DiT) blocks; QK-RMSNorm.",
"n_experts": null,
"active_experts": null,
"shared_experts": null,
"vocab_size": null,
"context_length": null,
"norm": "AdaLN",
"norm_placement": "pre",
"pos_encoding": "2D-RoPE",
"activation": "GeLU",
"tie_embeddings": false,
"vision": null,
"notes": "12B rectified-flow (flow-matching) text-to-image transformer; 57 blocks = 19 double-stream + 38 single-stream. Text via T5-XXL + CLIP-L; 16-ch VAE latent; guidance-distilled; axial RoPE; AdaLN timestep/guidance modulation.",
"sources": [
"https://huggingface.co/black-forest-labs/FLUX.1-dev"
],
"confidence": "verified"
},
{
"id": "stable-diffusion-3-5-large",
"name": "Stable Diffusion 3.5 Large",
"org": "Stability AI",
"family": "Stable Diffusion 3.5",
"released": "2024-10",
"license": "Stability Community",
"modality": "image-gen",
"decoder_type": "DiT (diffusion transformer)",
"params_total_B": 8,
"params_active_B": 8,
"n_layers": 38,
"d_model": 2432,
"d_ff": 9728,
"d_ff_moe": null,
"n_heads": 38,
"n_kv_heads": null,
"head_dim": 64,
"attention": "MMDiT",
"attention_detail": "Joint (multimodal) text+image attention with per-stream modulation, concatenated for one attention op; QK-RMSNorm.",
"n_experts": null,
"active_experts": null,
"shared_experts": null,
"vocab_size": null,
"context_length": null,
"norm": "AdaLN",
"norm_placement": "pre",
"pos_encoding": "learned",
"activation": "GeLU",
"tie_embeddings": false,
"vision": null,
"notes": "8B improved-MMDiT rectified-flow text-to-image model. Three text encoders (CLIP-L + OpenCLIP-bigG + T5-XXL); 16-ch VAE, patch_size 2, learned patch pos emb; QK-RMSNorm added over SD3 for stable high-res training.",
"sources": [
"https://huggingface.co/stabilityai/stable-diffusion-3.5-large",
"https://arxiv.org/abs/2403.03206"
],
"confidence": "verified"
},
{
"id": "qwen3-32b",
"name": "Qwen3-32B",
"org": "Alibaba",
"family": "Qwen",
"released": "2025-04",
"license": "Apache-2.0",
"modality": "text",
"decoder_type": "Dense",
"params_total_B": 32.8,
"params_active_B": 32.8,
"n_layers": 64,
"d_model": 5120,
"d_ff": 25600,
"d_ff_moe": null,
"n_heads": 64,
"n_kv_heads": 8,
"head_dim": 128,
"attention": "GQA",
"attention_detail": "GQA 64 query / 8 KV heads, head_dim 128 (decoupled from d_model); QK-Norm (RMSNorm on q,k)",
"n_experts": null,
"active_experts": null,
"shared_experts": null,
"vocab_size": 151936,
"context_length": 131072,
"norm": "RMSNorm",
"norm_placement": "pre",
"pos_encoding": "RoPE",
"activation": "SwiGLU",
"tie_embeddings": false,
"vision": null,
"notes": "Dense Qwen3 with QK-Norm on query/key for training stability; head_dim (128) decoupled from hidden_size. Native 32K context, extendable to 131K via YARN.",
"sources": [
"https://huggingface.co/Qwen/Qwen3-32B/raw/main/config.json",
"https://arxiv.org/abs/2505.09388"
],
"confidence": "verified"
},
{
"id": "qwen3-235b-a22b",
"name": "Qwen3-235B-A22B",
"org": "Alibaba",
"family": "Qwen",
"released": "2025-04",
"license": "Apache-2.0",
"modality": "text",
"decoder_type": "MoE",
"params_total_B": 235,
"params_active_B": 22,
"n_layers": 94,
"d_model": 4096,
"d_ff": 12288,
"d_ff_moe": 1536,
"n_heads": 64,
"n_kv_heads": 4,
"head_dim": 128,
"attention": "GQA",
"attention_detail": "GQA 64 query / 4 KV heads, head_dim 128; QK-Norm on q,k",
"n_experts": 128,
"active_experts": 8,
"shared_experts": 0,
"vocab_size": 151936,
"context_length": 131072,
"norm": "RMSNorm",
"norm_placement": "pre",
"pos_encoding": "RoPE",
"activation": "SwiGLU",
"tie_embeddings": false,
"vision": null,
"notes": "Fine-grained MoE with 128 experts, top-8 per token, no shared expert (unlike Qwen2-MoE); every layer is MoE. Uses QK-Norm; native 32K extendable to 131K via YARN.",
"sources": [
"https://huggingface.co/Qwen/Qwen3-235B-A22B/raw/main/config.json",
"https://arxiv.org/abs/2505.09388"
],
"confidence": "verified"
},
{
"id": "qwen3-next-80b-a3b",
"name": "Qwen3-Next-80B-A3B",
"org": "Alibaba",
"family": "Qwen",
"released": "2025-09",
"license": "Apache-2.0",
"modality": "text",
"decoder_type": "MoE",
"params_total_B": 80,
"params_active_B": 3,
"n_layers": 48,
"d_model": 2048,
"d_ff": 5120,
"d_ff_moe": 512,
"n_heads": 16,
"n_kv_heads": 2,
"head_dim": 256,
"attention": "hybrid",
"attention_detail": "3:1 hybrid — 36 Gated DeltaNet linear-attn layers + 12 full Gated Attention layers (16 q / 2 KV, head_dim 256, partial RoPE 0.25); full_attention_interval=4",
"n_experts": 512,
"active_experts": 10,
"shared_experts": 1,
"vocab_size": 151936,
"context_length": 262144,
"norm": "RMSNorm",
"norm_placement": "pre",
"pos_encoding": "partial-RoPE",
"activation": "SwiGLU",
"tie_embeddings": false,
"vision": null,
"notes": "Ultra-sparse hybrid: for every 3 Gated DeltaNet (linear) blocks there is 1 full-attention block; 512 experts with 10 routed + 1 shared active (only 3B of 80B active). Adds MTP; native 262K context.",
"sources": [
"https://huggingface.co/Qwen/Qwen3-Next-80B-A3B-Instruct/raw/main/config.json",
"https://vllm.ai/blog/2025-09-11-qwen3-next"
],
"confidence": "verified"
},
{
"id": "deepseek-v3",
"name": "DeepSeek-V3",
"org": "DeepSeek",
"family": "DeepSeek",
"released": "2024-12",
"license": "DeepSeek Model License",
"modality": "text",
"decoder_type": "MoE",
"params_total_B": 671,
"params_active_B": 37,
"n_layers": 61,
"d_model": 7168,
"d_ff": 18432,
"d_ff_moe": 2048,
"n_heads": 128,
"n_kv_heads": 128,
"head_dim": 192,
"attention": "MLA",
"attention_detail": "MLA: q_lora_rank=1536, kv_lora_rank=512, qk_nope=128, qk_rope=64 (q/k head_dim=192), v_head_dim=128",
"n_experts": 256,
"active_experts": 8,
"shared_experts": 1,
"vocab_size": 129280,
"context_length": 163840,
"norm": "RMSNorm",
"norm_placement": "pre",
"pos_encoding": "RoPE",
"activation": "SwiGLU",
"tie_embeddings": false,
"vision": null,
"notes": "Multi-head Latent Attention (MLA) with low-rank q/kv compression; fine-grained MoE (256 routed + 1 shared, top-8), first 3 layers dense; auxiliary-loss-free sigmoid routing + node-limited routing; MTP; FP8 training.",
"sources": [
"https://huggingface.co/deepseek-ai/DeepSeek-V3/raw/main/config.json",
"https://arxiv.org/abs/2412.19437"
],
"confidence": "verified"
},
{
"id": "deepseek-v3-2-exp",
"name": "DeepSeek-V3.2-Exp",
"org": "DeepSeek",
"family": "DeepSeek",
"released": "2025-09",
"license": "MIT",
"modality": "text",
"decoder_type": "MoE",
"params_total_B": 671,
"params_active_B": 37,
"n_layers": 61,
"d_model": 7168,
"d_ff": 18432,
"d_ff_moe": 2048,
"n_heads": 128,
"n_kv_heads": 128,
"head_dim": 192,
"attention": "sparse",
"attention_detail": "MLA + DeepSeek Sparse Attention (DSA): lightning indexer (index_n_heads=64, index_head_dim=128) selects top-2048 tokens per query; MLA q_lora=1536/kv_lora=512, qk_nope=128/qk_rope=64, v=128",
"n_experts": 256,
"active_experts": 8,
"shared_experts": 1,
"vocab_size": 129280,
"context_length": 163840,
"norm": "RMSNorm",
"norm_placement": "pre",
"pos_encoding": "RoPE",
"activation": "SwiGLU",
"tie_embeddings": false,
"vision": null,
"notes": "Same MLA+MoE backbone as V3 but adds DeepSeek Sparse Attention (DSA): a lightning indexer picks top-2048 tokens per query, cutting attention from O(L^2) to O(Lk) for long context while preserving quality.",
"sources": [
"https://huggingface.co/deepseek-ai/DeepSeek-V3.2-Exp/raw/main/config.json",
"https://github.com/deepseek-ai/DeepSeek-V3.2-Exp"
],
"confidence": "verified"
},
{
"id": "deepseek-r1",
"name": "DeepSeek-R1",
"org": "DeepSeek",
"family": "DeepSeek",
"released": "2025-01",
"license": "MIT",
"modality": "text",
"decoder_type": "MoE",
"params_total_B": 671,
"params_active_B": 37,
"n_layers": 61,
"d_model": 7168,
"d_ff": 18432,
"d_ff_moe": 2048,
"n_heads": 128,
"n_kv_heads": 128,
"head_dim": 192,
"attention": "MLA",
"attention_detail": "MLA identical to V3: q_lora=1536, kv_lora=512, qk_nope=128, qk_rope=64 (head_dim=192), v_head_dim=128",
"n_experts": 256,
"active_experts": 8,
"shared_experts": 1,
"vocab_size": 129280,
"context_length": 163840,
"norm": "RMSNorm",
"norm_placement": "pre",
"pos_encoding": "RoPE",
"activation": "SwiGLU",
"tie_embeddings": false,
"vision": null,
"notes": "Reasoning model with the SAME architecture as DeepSeek-V3 (MLA + fine-grained MoE, 256+1 experts, top-8); trained from V3-Base via large-scale RL. Config byte-identical to V3.",
"sources": [
"https://huggingface.co/deepseek-ai/DeepSeek-R1/raw/main/config.json",
"https://arxiv.org/abs/2501.12948"
],
"confidence": "verified"
}
];
